[package]
name = "fairchild-osdi"
version.workspace = true
edition = "2021"

[dependencies]
fairchild-core = { workspace = true }
libc      = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
fairchild-parser = { workspace = true }
indexmap = { workspace = true }
osdi-mock = { path = "../osdi-mock" }
