"""Live KiCad schematic → fairchild, over the KiCad IPC API (10.99+ / KiCad 11).

No export step, no toolbar button, no file watching: the REPL dials KiCad's
socket and pulls the netlist out of the *open* document.

    $ .venv/bin/python -i -m fairchild.kicad
    >>> sch                     # LiveSchematic, already connected
    >>> print(sch.report())
    >>> ckt = sch.circuit()     # fairchild.Circuit, deck already loaded
    >>> sch.refresh()           # re-pull after editing in KiCad

Requires `enable_server: true` in kicad_common.json (Preferences → Plugins →
Enable IPC API) and protos generated by ./regen_protos.sh from the same KiCad
source commit you are running.

Two seams worth knowing about, both verified against KiCad 10.99.0-1080:

* **Nets carry item KIIDs, not pin references.** `GetItemsById` will not
  resolve a pin KIID (it silently drops them and returns only the wires), so
  the net → (symbol, pin) join has to go the other way: every pin KIID from
  `GetItems(KOT_SCH_SYMBOL)` → `definition.items` appears in exactly one net.
  `PackSymbol` builds those from `GetPins(&aPath)`, so they are per-instance
  and per-sheet.

* **Per-instance SYMBOL field overrides are invisible over IPC.**
  `SCH_SYMBOL::Serialize` fills `definition.items` fields from `m_part` — the
  *library* symbol — and the proto has no instance field collection at all
  (only the 5 mandatory fields). So an instance that overrides `Sim.Params`
  reports the library default over IPC, silently. We read fields from the
  saved `.kicad_sch` instead and warn when the two disagree; see
  `Symbol.params_source`.

  Per-instance *sheet* fields need no workaround: `SheetSymbol.user_fields`
  does come over IPC, per instance, and is how a hierarchical sheet takes
  parameters — a symbol inside writes `l_m=${RING_HALF_LENGTH}` and each
  instance supplies its own value. That is the mechanism to reach for.

* **Whole-hierarchy reads need `sheet_path` cleared; joins need it kept.**
  `GetOpenDocuments` returns a specifier whose `sheet_path` is present but
  empty, which `api_handler_sch.cpp` reads as "filter to this sheet" and
  resolves to the root — 317 symbols instead of 1189 on a 91-sheet design,
  silently and with every pin resolving. Clear it to walk `Hierarchy()`. But a
  reused sheet is one `SCH_SYMBOL` packed once per path, so symbol and pin
  KIIDs repeat across instances and only `(sheet path, KIID)` is unique.
  `SheetSymbol.path` is the *container's* path, so an instance path is
  `path + (own id)`.
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path

import pynng

from fairchild.kicad._proto.common.commands.base_commands_pb2 import (
    GetVersion, GetVersionResponse)
from fairchild.kicad._proto.common.commands.editor_commands_pb2 import (
    GetItems, GetItemsResponse, GetOpenDocuments, GetOpenDocumentsResponse)
from fairchild.kicad._proto.common.envelope_pb2 import (
    ApiRequest, ApiResponse, ApiStatusCode)
from fairchild.kicad._proto.common.types.base_types_pb2 import DOCTYPE_SCHEMATIC
from fairchild.kicad._proto.common.types.enums_pb2 import KiCadObjectType
from fairchild.kicad._proto.schematic.schematic_commands_pb2 import (
    GetSchematicHierarchy, GetSchematicNetlist,
    SchematicHierarchyResponse, SchematicNetlistResponse)
from fairchild.kicad._proto.schematic.schematic_types_pb2 import (
    SchematicField, SchematicPin, SchematicSymbolInstance, SheetSymbol)

DEFAULT_SOCKET = "ipc:///tmp/kicad/api.sock"  # macOS hardcodes /tmp; see api_server.cpp

_MANDATORY_FIELDS = frozenset(
    ("Reference", "Value", "Footprint", "Datasheet", "Description"))

# Model node order per SPICE primitive, used to invert Sim.Pins. Sim.Pins is
# written `<symbolPinNumber>=<modelPinName>` (sim_model_serializer.cpp:274) so
# it maps symbol→model; emitting needs model→symbol, in the model's own order.
# ponytail: two-terminal only. Q/M name their nodes (C/B/E, D/G/S/B) and would
# need their own rows; until one shows up we fall back to pin-number order and
# say so rather than guessing a transposition.
_MODEL_NODE_ORDER = {
    "R": ("+", "-"), "L": ("+", "-"), "C": ("+", "-"),
    "V": ("+", "-"), "I": ("+", "-"), "D": ("+", "-"),
}

# Reference-designator prefix → primitive, for symbols with no Sim.Device.
# KiCad leaves it off passives (Device:R_US carries no Sim.Device at all) and
# infers the model from the refdes, so we have to as well.
_REFDES_PRIMITIVE = {"R": "R", "L": "L", "C": "C", "V": "V", "I": "I", "D": "D"}

_SUBST_RE = re.compile(r"\$\{([^}]+)\}")

# KiCad Sim.Params name → position in the fairchild/SPICE waveform argument
# list. fairchild parses SIN(vo va freq td theta phase) — waveforms.rs:69.
_WAVEFORMS = {
    "SIN": ("SIN", ("dc", "ampl", "f", "delay", "damping", "phase")),
    "PULSE": ("PULSE", ("initial", "pulsed", "delay", "rise", "fall", "width",
                        "period")),
}
# Bookkeeping KiCad writes itself; never a simulation parameter.
_IGNORED_FIELDS = frozenset(
    ("Intersheetrefs", "Sheetname", "Sheetfile", "ki_keywords", "ki_fp_filters",
     "ki_locked", "LCSC Part #"))

# Port kind per native photonic model, shared with scripts/kicad_to_fairchild.py
# so the IPC path and the SPICE-export path can't disagree about which pins are
# optical bundles.
# ponytail: sys.path poke because the converter lives in scripts/, not a package.
# Move PORT_SCHEMA into the device registry if a third consumer shows up.
import sys as _sys

_sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "scripts"))
from kicad_to_fairchild import (  # type: ignore  # noqa: E402
    BUNDLE_BRIDGE_MODELS, GROUND_NETS, PORT_SCHEMA)


class ApiError(RuntimeError):
    pass


class KiCad:
    """Minimal IPC client: nng REQ socket carrying protobuf `ApiRequest`s.

    Token handling matches kipy — send an empty token and adopt whatever KiCad
    replies with, which is what lets an external process connect at all (KiCad
    only injects KICAD_API_TOKEN into plugins it launches itself).
    """

    def __init__(self, socket: str | None = None, client_name: str = "fairchild",
                 timeout_ms: int = 120_000):
        # Generous by default: a whole-hierarchy GetItems on a real chip is not
        # fast (giona_fc = 91 sheets / 1189 symbols) and a timeout mid-pull is
        # indistinguishable from a socket problem.
        self.socket = socket or os.environ.get("KICAD_API_SOCKET", DEFAULT_SOCKET)
        self.client_name = f"{client_name}-{os.getpid()}"
        self.token = os.environ.get("KICAD_API_TOKEN", "")
        try:
            self._conn = pynng.Req0(dial=self.socket, block_on_dial=True,
                                    recv_timeout=timeout_ms, send_timeout=timeout_ms)
        except pynng.ConnectionRefused as e:
            # "Connection refused" on its own sends people hunting for a network
            # problem; there are only really two causes.
            raise ApiError(
                f"no KiCad listening on {self.socket} — either KiCad is not "
                f"running, or its IPC API is off (Preferences → Plugins → "
                f"Enable KiCad API, i.e. \"enable_server\": true in "
                f"kicad_common.json)") from e

    def send(self, msg, reply_type, retries: int = 40):
        """Send one request, waiting out AS_BUSY / AS_NOT_READY.

        KiCad answers AS_BUSY whenever the user is mid-gesture — a dialog open,
        a drag in progress — and AS_NOT_READY just after launch. Neither is an
        error for a tool that talks to a GUI somebody is actively using, so
        treat them as backpressure and retry instead of exploding in the REPL.
        """
        import time
        env = ApiRequest()
        env.message.Pack(msg)
        env.header.kicad_token = self.token
        env.header.client_name = self.client_name
        payload = env.SerializeToString()
        transient = {ApiStatusCode.AS_BUSY, ApiStatusCode.AS_NOT_READY}

        for attempt in range(retries + 1):
            self._conn.send(payload)
            rep = ApiResponse()
            rep.ParseFromString(self._conn.recv())
            if not self.token:
                self.token = rep.header.kicad_token
                # The token goes in every later request, so refresh the payload.
                env.header.kicad_token = self.token
                payload = env.SerializeToString()
            if rep.status.status == ApiStatusCode.AS_OK:
                out = reply_type()
                rep.message.Unpack(out)
                return out
            if rep.status.status in transient and attempt < retries:
                time.sleep(min(0.25 * (attempt + 1), 2.0))
                continue
            hint = ""
            if rep.status.status == ApiStatusCode.AS_BUSY:
                # CanAcceptApiCommands() is just IsEnabled(), and a wx frame is
                # disabled while a modal dialog is up. "Busy" almost always means
                # a dialog is open, which is not obvious from the message.
                hint = (" — a modal dialog is probably open in eeschema; "
                        "close it and retry")
            raise ApiError(f"{ApiStatusCode.Name(rep.status.status)}: "
                           f"{rep.status.error_message}{hint}")

    @property
    def version(self) -> str:
        return self.send(GetVersion(), GetVersionResponse).version.full_version


def _sexpr_symbol_fields(text: str) -> dict[str, dict[str, str]]:
    """{symbol uuid: {field name: value}} for placed symbols in a .kicad_sch.

    Paren-matched rather than regexed, because a `(property "x" "(a)")` value
    can contain anything. Blocks with no depth-1 `(uuid …)` are `lib_symbols`
    entries and their nested unit sub-symbols, which we skip: the whole point
    is to read what the *placed* symbol says.
    """
    out: dict[str, dict[str, str]] = {}
    for m in re.finditer(r"\(symbol\b", text):
        depth, i, n = 0, m.start(), len(text)
        while i < n:  # find the matching close paren, honouring string literals
            c = text[i]
            if c == '"':
                i += 1
                while i < n and text[i] != '"':
                    i += 2 if text[i] == "\\" else 1
            elif c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        block = text[m.start():i + 1]
        inner = block[len("(symbol"):]
        uuid = re.search(r'^\s*\(uuid\s+"?([^")\s]+)"?\)', inner, re.M)
        if not uuid:
            continue
        fields = {k: v for k, v in re.findall(
            r'\(property\s+"((?:[^"\\]|\\.)*)"\s+"((?:[^"\\]|\\.)*)"', inner)}
        out[uuid.group(1)] = fields
    return out


@dataclass
class Pin:
    number: str
    name: str
    kiid: str
    net: str = ""
    #: Absolute schematic position in nanometres, as packed by PackSymbol from
    #: GetPins(&aPath) — needed to place an annotation next to the right pin.
    xy_nm: tuple[int, int] = (0, 0)

    @property
    def position_mm(self) -> tuple[float, float]:
        return (self.xy_nm[0] / 1e6, self.xy_nm[1] / 1e6)

    @property
    def order(self) -> tuple:
        """Sort key: numeric pin numbers numerically, oddballs alphabetically."""
        return (0, int(self.number), "") if self.number.isdigit() else (1, 0, self.number)


@dataclass
class Sheet:
    """A hierarchical sheet instance — fairchild's subcircuit, KiCad-side.

    `fields` are the sheet's `user_fields`, which are how parameters get passed
    into a sub-sheet: a symbol inside `pn_mrm_mod.kicad_sch` writes
    `l_m=${RING_HALF_LENGTH}` and each of the 8 instances supplies its own
    value. Unlike *symbol* instance fields, these are per-instance AND visible
    over IPC, so they need no file fallback.
    """
    path: tuple[str, ...]
    name: str
    filename: str
    fields: dict[str, str] = field(default_factory=dict)


@dataclass
class Symbol:
    ref: str
    lib_id: str
    kiid: str
    params: str
    #: KIID path of the sheet instance this symbol sits on. NOT redundant with
    #: `kiid`: a reused sheet is one SCH_SYMBOL packed once per path, so `kiid`
    #: (and every pin kiid under it) repeats across instances and only
    #: (path, kiid) is unique. giona_fc: 1189 instances, 531 symbol kiids.
    path: tuple[str, ...] = ()
    sheet: str = ""
    pins: list[Pin] = field(default_factory=list)
    #: All non-mandatory fields read off the saved sheet file, including custom
    #: ones (R_WB_PAR, RING_HALF_LENGTH, …) that IPC cannot see.
    fields: dict[str, str] = field(default_factory=dict)
    params_source: str = "ipc"
    excluded_from_sim: bool = False

    #: `Value` field. Instance-level and delivered over IPC (it is one of the
    #: five mandatory fields), so unlike Sim.Params it needs no file fallback —
    #: this is where R/L/C/V/I values live.
    value: str = ""

    @property
    def is_power_flag(self) -> bool:
        """power:GND / VBUS / VCC symbols name a net, they aren't devices."""
        return self.lib_id.startswith("power:")

    @property
    def primitive(self) -> str:
        """SPICE primitive letter, or "" if this is not an electrical part.

        `Sim.Device` wins when present; KiCad omits it on passives and infers
        from the refdes, so we do too — but only for prefixes we know, so a
        `PS_PN_TH1` never gets mistaken for something with a P model.
        """
        dev = self.fields.get("Sim.Device", "").strip().upper()
        if dev in _MODEL_NODE_ORDER:
            return dev
        if dev in ("SPICE", "SUBCKT"):
            return ""
        m = re.match(r"^([A-Z])\d", self.ref.upper())
        return _REFDES_PRIMITIVE.get(m.group(1), "") if m else ""

    @property
    def model(self) -> str:
        m = re.search(r"\bmodel=(\S+)", self.params)
        return m.group(1) if m else ""

    @property
    def param_dict(self) -> dict[str, str]:
        return {k: v for k, v in
                (kv.split("=", 1) for kv in self.params.split() if "=" in kv)
                if k not in ("type", "model")}

    def sorted_pins(self) -> list[Pin]:
        return sorted(self.pins, key=lambda p: p.order)


def _sanitise(net: str) -> str:
    """KiCad net name → a SPICE-legal one. NOT injective on its own.

    `+` and `-` map to `p`/`n` rather than `_` because they are the common case
    and collapsing them silently shorts device terminals: `PD1+` and `PD1-` both
    became `…_PD1_`, which shorted all 8 photodetectors in giona_fc and made the
    operating point unsolvable. Any residual collision is resolved by
    `LiveSchematic._build_net_map`, which is what callers should go through —
    this function alone cannot see its siblings.
    """
    if net in GROUND_NETS or net.upper() in ("GND", "GNDA", "VSS"):
        return "0"
    n = re.sub(r"^Net-\((.*)\)$", r"\1", net)
    n = re.sub(r"^unconnected-\((.*)\)$", r"nc_\1", n)
    # Polarity suffix is the collision that matters; other separators can all
    # collapse to '_' since the disambiguation pass will catch any leftovers.
    n = re.sub(r"\+$", "_p", n)
    n = re.sub(r"-$", "_n", n)
    return re.sub(r"[^A-Za-z0-9_]", "_", n)


class LiveSchematic:
    def __init__(self, kicad: KiCad | None = None):
        self.k = kicad or KiCad()
        self.doc = None
        self.symbols: list[Symbol] = []
        self.sheets = None
        self.warnings: list[str] = []
        self.refresh()

    # ── pull ────────────────────────────────────────────────────────────────
    def refresh(self) -> "LiveSchematic":
        docs = self.k.send(GetOpenDocuments(type=DOCTYPE_SCHEMATIC),
                           GetOpenDocumentsResponse)
        if not docs.documents:
            raise ApiError("no schematic open in KiCad")
        self.doc = docs.documents[0]
        self.sheets = self.k.send(GetSchematicHierarchy(document=self.doc),
                                  SchematicHierarchyResponse).top_level_sheets
        self._text_vars = self._project_text_vars()
        self.warnings = []
        self._load_sheet_params()
        self._load_symbols()
        self._load_nets()
        self._build_net_map()
        self._overlay_instance_params()
        self._resolve_sheet_params()
        return self

    def _build_net_map(self) -> None:
        """raw KiCad net name → unique SPICE net name.

        Sanitisation is lossy, and two nets that collapse to one name are a
        short circuit in the emitted deck — silent, and fatal to convergence
        rather than to parsing. So build the mapping once, globally, and
        disambiguate anything that would collide. Ground is exempt: every
        ground alias is *meant* to become node 0.
        """
        raws = sorted({p.net for s in self.symbols for p in s.pins})
        taken: dict[str, str] = {}   # safe name → the raw that claimed it
        self.net_name: dict[str, str] = {}
        for raw in raws:
            safe = _sanitise(raw)
            if safe == "0":
                self.net_name[raw] = safe
                continue
            if safe in taken:
                base, i = safe, 2
                while safe in taken:
                    safe = f"{base}_{i}"
                    i += 1
                self.warnings.append(
                    f"net name collision: {raw!r} and {taken[base]!r} both "
                    f"sanitise to {base!r}; renamed this one to {safe!r} — "
                    f"without this they would be one net, i.e. a short")
            taken[safe] = raw
            self.net_name[raw] = safe

    def net(self, raw: str) -> str:
        """Deck net name for a KiCad net. Falls back for nets added since refresh."""
        return self.net_name.get(raw) or _sanitise(raw)

    def _project_text_vars(self) -> dict[str, str]:
        """Project-wide ${} substitutions — the outermost parameter scope."""
        try:
            from fairchild.kicad._proto.common.commands.base_commands_pb2 import (
                GetTextVariables)
            from fairchild.kicad._proto.common.types.project_settings_pb2 import (
                TextVariables)
            return dict(self.k.send(GetTextVariables(), TextVariables).variables)
        except Exception as e:  # not fatal: sheet fields cover the common case
            self.warnings.append(f"project text variables unavailable ({e})")
            return {}

    def _load_sheet_params(self) -> None:
        req = GetItems(types=[KiCadObjectType.KOT_SCH_SHEET])
        req.header.document.CopyFrom(self.doc)
        req.header.document.ClearField("sheet_path")
        self.sheet_params: dict[tuple[str, ...], Sheet] = {}
        for any_it in self.k.send(req, GetItemsResponse).items:
            sh = SheetSymbol()
            if not any_it.Unpack(sh):
                continue
            # SheetSymbol.path is the path of the sheet's *container*, not of the
            # instance; the instance path appends the sheet's own KIID. Keying on
            # sh.path alone collapses every sibling sheet onto one entry (90 → 11
            # on giona_fc) and loses all but one set of parameters.
            path = tuple(k.value for k in sh.path.path) + (sh.id.value,)
            self.sheet_params[path] = Sheet(
                path=path,
                name=sh.name_field.text.text,
                filename=sh.filename_field.text.text,
                fields={f.name: f.text.text for f in sh.user_fields})

    def _resolve_sheet_params(self) -> None:
        """Substitute `${NAME}` in Sim.Params from the enclosing sheet chain.

        Inner sheets win over outer ones, which is the same shadowing a nested
        subckt gets. Project text variables are the outermost scope.
        """
        for s in self.symbols:
            # Value carries ${} too — an inductor written as ${L_WB} is just as
            # parameterised as a phase shifter's Sim.Params.
            if "${" not in s.params and "${" not in s.value:
                continue
            env = dict(self._text_vars)
            for depth in range(len(s.path) + 1):  # outermost → innermost
                sheet = self.sheet_params.get(s.path[:depth])
                if sheet:
                    env.update(sheet.fields)
            def sub(text: str) -> str:
                return _SUBST_RE.sub(
                    lambda m: env.get(m.group(1), m.group(0)), text)

            s.params, s.value = sub(s.params), sub(s.value)
            for what, text in (("Sim.Params", s.params), ("Value", s.value)):
                if "${" in text:
                    left = sorted(set(_SUBST_RE.findall(text)))
                    self.warnings.append(
                        f"{s.ref}: unresolved sheet parameter(s) {left} in {what}")

    def _load_symbols(self) -> None:
        req = GetItems(types=[KiCadObjectType.KOT_SCH_SYMBOL])
        req.header.document.CopyFrom(self.doc)
        # GetOpenDocuments hands back a DocumentSpecifier whose `sheet_path` is
        # *present but empty*, and api_handler_sch.cpp treats has_sheet_path()
        # as "filter to this sheet", resolving an empty KIID path to the root.
        # Passing the document through verbatim therefore returns the root sheet
        # only — silently, and looking perfectly healthy. giona_fc: 317 symbols
        # instead of 1189. Clearing the field makes the handler walk Hierarchy().
        req.header.document.ClearField("sheet_path")
        by_path = self._sheet_names()
        self.symbols = []
        for any_it in self.k.send(req, GetItemsResponse).items:
            si = SchematicSymbolInstance()
            if not any_it.Unpack(si):
                continue
            fields: dict[str, str] = {}
            pins = []
            for ch in si.definition.items:
                if ch.item.type_url.endswith("SchematicField"):
                    f = SchematicField()
                    ch.item.Unpack(f)
                    if f.name not in _MANDATORY_FIELDS:
                        fields[f.name] = f.text.text
                elif ch.item.type_url.endswith("SchematicPin"):
                    p = SchematicPin()
                    ch.item.Unpack(p)
                    pins.append(Pin(number=p.number, name=p.name, kiid=p.id.value,
                                    xy_nm=(p.position.x_nm, p.position.y_nm)))
            path = tuple(k.value for k in si.path.path)
            self.symbols.append(Symbol(
                ref=si.reference_field.text.text,
                lib_id=f"{si.definition.id.library_nickname}:{si.definition.id.entry_name}",
                kiid=si.id.value, params=fields.get("Sim.Params", ""), path=path,
                sheet=by_path.get(path, ""), pins=pins, fields=fields,
                value=si.value_field.text.text,
                excluded_from_sim=si.attributes.exclude_from_simulation))

    def _sheet_names(self) -> dict[tuple[str, ...], str]:
        """KIID path → source filename, for every sheet instance."""
        out: dict[tuple[str, ...], str] = {}

        def walk(sheets):
            for s in sheets:
                out[tuple(k.value for k in s.path.path)] = s.filename
                walk(s.children)

        walk(self.sheets or [])
        return out

    def _load_nets(self) -> None:
        nl = self.k.send(GetSchematicNetlist(document=self.doc),
                         SchematicNetlistResponse)
        # Join on (sheet path, pin KIID), never on pin KIID alone. A reused
        # sheet is one SCH_SYMBOL packed once per path, so its pin KIIDs repeat
        # across instances — giona_fc has 2896 pins but only 978 distinct pin
        # KIIDs, and a KIID-keyed dict silently hands every copy's net to
        # whichever instance landed in the dict last. That is why
        # SchematicNetSheetContents carries a `path` alongside its items.
        by_key = {(s.path, p.kiid): p for s in self.symbols for p in s.pins}
        hits = 0
        for net in nl.nets:
            for sheet in net.sheets:
                path = tuple(k.value for k in sheet.path.path)
                for item in sheet.items:
                    pin = by_key.get((path, item.value))
                    if pin is not None:
                        pin.net = net.name
                        hits += 1
        missing = [f"{s.ref}.{p.number}" for s in self.symbols
                   for p in s.pins if not p.net]
        if missing:
            self.warnings.append(
                f"{len(missing)} pin(s) matched no net: {', '.join(missing[:6])}"
                f"{' …' if len(missing) > 6 else ''}")
        self._net_hits = hits

    def _overlay_instance_params(self) -> None:
        """IPC reports the LIBRARY Sim.Params, so read instance overrides off disk.

        See the module docstring: SCH_SYMBOL::Serialize takes non-mandatory
        fields from m_part. Anything overridden on the placed symbol is
        invisible over IPC, so a schematic that looks fine here would simulate
        with the wrong parameters. Reading the saved file is the cheap fix; the
        real one is an upstream patch adding instance fields to the proto.

        Keyed on symbol UUID, not reference: a reused sheet stores its symbol
        (and its field values) once in the file while each sheet instance gets
        its own reference designator, so reference-keyed lookup misses every
        reuse. That also means a *symbol* field cannot vary between instances of
        one sheet. To parameterise per instance, put the value on the sheet
        (`Sheet.fields`, resolved by `_resolve_sheet_params`) — those are
        per-instance and visible over IPC.
        """
        files = self.sheet_files()
        if not files:
            self.warnings.append("could not locate any .kicad_sch; params are "
                                 "library defaults and may be stale")
            return
        on_disk: dict[str, dict[str, str]] = {}
        for f in files:
            try:
                on_disk.update(_sexpr_symbol_fields(f.read_text()))
            except OSError as e:
                self.warnings.append(f"could not read {f.name}: {e}")
        overridden = []
        for s in self.symbols:
            fields = on_disk.get(s.kiid)
            if not fields:
                continue
            # The file is authoritative for non-mandatory fields (IPC gives the
            # library's). Value is NOT taken from the file: it is mandatory, so
            # IPC already has the live per-instance one.
            s.fields.update({k: v for k, v in fields.items()
                             if k not in _MANDATORY_FIELDS})
            disk = fields.get("Sim.Params")
            if disk is not None and disk != s.params:
                s.params, s.params_source = disk, "file"
                overridden.append(s.ref)
        if overridden:
            self.warnings.append(
                f"{len(overridden)} symbol(s) override Sim.Params per instance "
                f"({', '.join(overridden[:6])}); used the saved file, so unsaved "
                f"parameter edits are NOT reflected (connectivity still is)")

    def sheet_files(self) -> list[Path]:
        """Every distinct .kicad_sch backing the hierarchy, root first."""
        root = Path(self.doc.project.path)
        seen, out = set(), []
        for name in self._sheet_names().values():
            if name and name not in seen:
                seen.add(name)
                p = root / name
                if p.exists():
                    out.append(p)
        return out

    def custom_fields(self) -> dict[str, dict[str, str]]:
        """{field name: {symbol ref: value}} for every non-Sim custom field."""
        out: dict[str, dict[str, str]] = {}
        for s in self.symbols:
            for k, v in s.fields.items():
                if not k.startswith("Sim.") and k not in _IGNORED_FIELDS:
                    out.setdefault(k, {})[s.ref] = v
        return out

    # ── emit ────────────────────────────────────────────────────────────────
    def _bundle_widths(self) -> dict[str, int]:
        """Channel count per optical net.

        A KiCad wire carries no width — only `fc_mux`/`fc_demux` pin one down,
        by having N channel pins and one bus pin. Everything else is
        `BundleArity::Aware` (see bundles.rs), meaning all of an instance's
        optical ports must agree on a width, so the bus width has to spread
        outward from the bridges to every net it can reach. Without this pass a
        dangling optical pin next to a bus port defaults to 1 channel and
        fairchild rightly refuses the instance.

        Propagation stops at bridges: their channel side stays pinned at 1,
        which is the whole point of a bridge. Any genuine conflict (a Scalar
        device such as `fc_cw_laser` sitting on a wide net) is left for
        fairchild to reject, so its arity table stays the only copy.
        """
        pinned: dict[str, int] = {}
        for s in self.symbols:
            if s.model not in BUNDLE_BRIDGE_MODELS:
                continue
            pins = s.sorted_pins()
            bus_i = next((i for i, p in enumerate(pins) if p.name == "bus"), 0)
            for i, p in enumerate(pins):
                pinned[self.net(p.net)] = max(len(pins) - 1, 1) if i == bus_i else 1

        widths = dict(pinned)
        for _ in range(len(self.symbols) + 1):  # fixpoint; can't cycle more than once per device
            changed = False
            for s in self.symbols:
                if s.model in BUNDLE_BRIDGE_MODELS:
                    continue
                schema = PORT_SCHEMA.get(s.model)
                if schema is None:
                    continue
                nets = [self.net(p.net) for kind, p in zip(schema, s.sorted_pins())
                        if kind == "bundle"]
                w = max((widths.get(n, 1) for n in nets), default=1)
                for n in nets:
                    if n != "0" and n not in pinned and widths.get(n, 1) != w:
                        widths[n], changed = w, True
            if not changed:
                break
        return widths

    def _model_ordered_pins(self, s: Symbol, kind: str) -> list[Pin]:
        """Pins in the model's node order, honouring Sim.Pins.

        Sim.Pins reads `<symbolPinNumber>=<modelPinName>`, so it must be
        inverted before use. Getting this backwards silently transposes the
        terminals of every source and diode in the design, which is why an
        unmappable Sim.Pins warns instead of falling through quietly.
        """
        order = _MODEL_NODE_ORDER.get(kind)
        raw = s.fields.get("Sim.Pins", "").strip()
        if not raw or not order:
            return s.sorted_pins()
        sym_to_model = dict(
            kv.split("=", 1) for kv in raw.split() if kv.count("=") == 1)
        model_to_sym = {v: k for k, v in sym_to_model.items()}
        by_number = {p.number: p for p in s.pins}
        try:
            return [by_number[model_to_sym[node]] for node in order]
        except KeyError:
            self.warnings.append(
                f"{s.ref}: Sim.Pins {raw!r} does not cover model nodes "
                f"{list(order)}; fell back to pin-number order, so check its "
                f"terminals")
            return s.sorted_pins()

    def _emit_electrical(self, s: Symbol, kind: str, nets: list[str]) -> str:
        """One SPICE primitive line: R/L/C value, or a V/I DC level or waveform.

        Precedence follows sim_model.cpp:442 — Sim.Params first, Value only as
        the fallback. That matters for VSIN, whose Value is the literal string
        "VSIN" while the real numbers live in Sim.Params.
        """
        # KiCad refdes already carries the primitive letter (R1, C12), so only
        # prefix when it doesn't — otherwise every element comes out as RR1.
        name = s.ref if s.ref.upper().startswith(kind) else f"{kind}{s.ref}"
        head = f"{name} {' '.join(nets)}"
        sim_type = s.fields.get("Sim.Type", "").strip().upper()

        if kind in ("R", "L", "C"):
            if not s.value:
                self.warnings.append(f"{s.ref}: no Value for a {kind}; emitted 0")
            return f"{head} {s.value or 0}"

        # V / I
        if sim_type in _WAVEFORMS and s.params:
            fn, argnames = _WAVEFORMS[sim_type]
            p = s.param_dict
            args = [p.get(n, "0") for n in argnames]
            while len(args) > 3 and args[-1] == "0":  # trailing defaults
                args.pop()
            if "ac" in p:
                self.warnings.append(
                    f"{s.ref}: ac={p['ac']} dropped — fairchild has no AC "
                    f"magnitude on a source line (waveforms.rs), so an .ac "
                    f"sweep will see this source as silent")
            return f"{head} {fn}({' '.join(args)})"

        if sim_type and sim_type not in ("DC", "") and sim_type not in _WAVEFORMS:
            self.warnings.append(
                f"{s.ref}: Sim.Type={sim_type!r} not supported; emitted as DC")
        return f"{head} DC {s.value or 0}"

    def nets(self) -> dict[str, list[str]]:
        out: dict[str, list[str]] = {}
        for s in self.symbols:
            for p in s.pins:
                out.setdefault(self.net(p.net), []).append(f"{s.ref}.{p.name or p.number}")
        return out

    @property
    def current_sheet(self) -> Sheet | None:
        """The sheet instance the user is looking at, or None at the root.

        `handleGetOpenDocuments` packs `GetCurrentSheet()` into the document
        specifier, so this tracks navigation in the editor — which makes it the
        natural scope for a toolbar action: descend into a block, press the
        button, simulate that block.
        """
        path = tuple(k.value for k in self.doc.sheet_path.path)
        return self.sheet_params.get(path)

    def scopes(self) -> dict[str, int]:
        """{sheet instance name: symbol count in its subtree} — deck() targets."""
        out = {}
        for sh in self.sheet_params.values():
            n = sum(1 for s in self.symbols if s.path[:len(sh.path)] == sh.path)
            if n:
                out[sh.name] = n
        return out

    def scoped(self, scope: str) -> list[Symbol]:
        """Symbols in the subtree of the sheet instance named `scope`."""
        paths = [sh.path for sh in self.sheet_params.values() if sh.name == scope]
        if not paths:
            raise KeyError(f"no sheet named {scope!r}; try {sorted(self.scopes())}")
        return [s for s in self.symbols
                if any(s.path[:len(p)] == p for p in paths)]

    def deck(self, analysis: str = ".op", title: str | None = None,
             scope: str | None = None, symbols: list | None = None) -> str:
        """Emit a fairchild netlist. Positional ports follow KiCad pin number order.

        `scope` restricts the deck to one hierarchical sheet's subtree, so a
        block can be exercised on its own without carving out a new schematic.
        Boundary nets of the subtree come out undriven — that is the point of
        isolating it, but it does mean the operating point is not the one the
        block sees in situ.

        `symbols` overrides both and emits exactly the instances given, which is
        what makes additive bisection possible: start from a deck that solves and
        add groups until it stops.
        """
        title = title or (self.doc.project.name if self.doc else "kicad")
        lines = [f"* fairchild deck from live KiCad schematic: {title}",
                 f"* kicad {self.k.version}", ""]
        import collections
        if symbols is None:
            symbols = self.scoped(scope) if scope else self.symbols
        if scope:
            lines[0] += f"  [scope: {scope}, {len(symbols)} symbols]"
        widths = self._bundle_widths()
        # Declare only the bundles this deck actually references — `widths` spans
        # the whole design, and a scoped deck must not drag in 700 foreign ports.
        used: set[str] = set()
        skipped: collections.Counter = collections.Counter()
        body = []
        for s in sorted(symbols, key=lambda s: s.ref):
            if s.excluded_from_sim:
                body.append(f"* {s.ref} excluded from simulation")
                continue
            if s.is_power_flag:
                continue  # names a net, isn't a device; _sanitise maps GND → 0
            kind = s.primitive
            if kind:
                ordered = self._model_ordered_pins(s, kind)
                body.append(self._emit_electrical(
                    s, kind, [self.net(p.net) for p in ordered]))
                continue
            pins = s.sorted_pins()
            nets = [self.net(p.net) for p in pins]
            if s.model in BUNDLE_BRIDGE_MODELS:
                # Mux/demux arity is set by how many channel pins the symbol has,
                # so there is no fixed PORT_SCHEMA entry. Every port is optical,
                # and the bus side carries all the channels at once (width from
                # _bundle_widths).
                schema = ["bundle"] * len(pins)
            else:
                schema = PORT_SCHEMA.get(s.model)
                if schema is None:
                    body.append(f"* {s.ref}: unknown model {s.model!r} "
                                f"({s.lib_id}) — not emitted")
                    skipped[s.model or s.lib_id] += 1
                    continue
                if len(schema) != len(nets):
                    self.warnings.append(
                        f"{s.ref}: {len(nets)} pins but PORT_SCHEMA[{s.model}] "
                        f"expects {len(schema)}")
            for kind, net in zip(schema, nets):
                if kind == "bundle" and net != "0":
                    used.add(net)
            kv = " ".join(f"{k}={v}" for k, v in s.param_dict.items())
            body.append(f"X{s.ref} {' '.join(nets)} {s.model}{' ' + kv if kv else ''}")
        if skipped:
            self.warnings.append(
                "no emitter for " + ", ".join(f"{k or '(no Sim.Params)'}×{n}"
                                              for k, n in skipped.most_common())
                + " — electrical primitives (R/L/C/V/I) and power flags are not "
                  "yet emitted, so this deck is the photonics only")
        lines += [f".optical_port {b}" + (f" {widths[b]}" if widths.get(b, 1) > 1
                                          else "")
                  for b in sorted(used)]
        lines += ["", *body, "", analysis, ".end", ""]
        return "\n".join(lines)

    def circuit(self, analysis: str = ".op", scope: str | None = None):
        """Return a fairchild.Circuit with the live deck already loaded."""
        import fairchild
        ckt = fairchild.Circuit()
        ckt.load_str(self.deck(analysis, scope=scope))
        return ckt

    # ── inspect ─────────────────────────────────────────────────────────────
    def report(self, detail: bool | None = None) -> str:
        """Summary by default; per-pin detail when `detail=True`.

        Auto-summarises above 60 symbols — a per-pin dump of a real chip is
        thousands of lines and hides the warnings underneath it.
        """
        import collections
        if detail is None:
            detail = len(self.symbols) <= 60
        out = [f"kicad     {self.k.version}",
               f"project   {self.doc.project.name} ({self.doc.project.path})",
               f"sheets    {self._sheet_summary()}",
               f"symbols   {len(self.symbols)}"
               f"  ({sum(len(s.pins) for s in self.symbols)} pins, "
               f"{self._net_hits} pin→net joins)",
               ""]
        pop = collections.Counter(
            s.model or ("power flag" if s.is_power_flag else f"[{s.lib_id}]")
            for s in self.symbols)
        out.append("population:")
        for name, n in pop.most_common():
            emit = "" if name in PORT_SCHEMA or name in BUNDLE_BRIDGE_MODELS \
                else "   (not emitted)"
            out.append(f"  {n:>5}  {name}{emit}")
        params = [s for s in self.sheet_params.values() if s.fields]
        if params:
            out += ["", "sheet parameters (per-instance, live over IPC):"]
            for sh in sorted(params, key=lambda s: (s.filename, s.name)):
                kv = " ".join(f"{k}={v}" for k, v in sh.fields.items())
                out.append(f"  {sh.name:<20} {sh.filename:<26} {kv}")
        custom = self.custom_fields()
        if custom:
            out += ["", "symbol custom fields (from the saved sheet files):"]
            for name, vals in sorted(custom.items()):
                uniq = sorted(set(vals.values()))
                out.append(f"  {name}: {len(vals)} symbol(s), "
                           f"value(s) {uniq[:4]}{' …' if len(uniq) > 4 else ''}")
        widths = self._bundle_widths()
        if detail:
            out.append("")
            for s in sorted(self.symbols, key=lambda s: s.ref):
                src = "" if s.params_source == "ipc" else f"  [{s.params_source}]"
                out.append(f"  {s.ref:<8} {s.model:<16}{src}")
                for p in s.sorted_pins():
                    net = self.net(p.net)
                    w = widths.get(net)
                    out.append(f"      {p.number:>3} {p.name or '-':<10} {net}"
                               f"{f'  ({w}ch)' if w and w > 1 else ''}")
        if self.warnings:
            out += ["", "warnings:"] + [f"  ! {w}" for w in self.warnings]
        return "\n".join(out)

    def _sheet_summary(self) -> str:
        def walk(sheets):
            n = len(sheets)
            for s in sheets:
                n += walk(s.children)
            return n
        total = walk(self.sheets or [])
        return f"{total} ({self.sheets[0].filename if self.sheets else '?'})"


def connect(socket: str | None = None) -> LiveSchematic:
    return LiveSchematic(KiCad(socket))


def demo() -> None:
    """Self-check against whatever schematic is open. Needs a running KiCad."""
    sch = connect()
    assert sch.doc is not None
    assert sch.symbols, "no symbols returned"
    assert sch.k.version.startswith("10.") or sch.k.version.startswith("11."), sch.k.version

    joined = sum(1 for s in sch.symbols for p in s.pins if p.net)
    total = sum(len(s.pins) for s in sch.symbols)
    assert joined == total, f"pin→net join incomplete: {joined}/{total}"

    # (sheet path, pin KIID) must be unique, or the join aliases pins between
    # instances of a reused sheet. Pin KIID ALONE is not unique — giona_fc has
    # 2896 pins over 978 distinct pin KIIDs — so this pair is the invariant.
    keys = [(s.path, p.kiid) for s in sch.symbols for p in s.pins]
    assert len(set(keys)) == len(keys), "(sheet path, pin KIID) is not unique"

    # A hierarchical design must not silently collapse to its root sheet.
    if len(sch.sheet_params) > 1:
        depths = {len(s.path) for s in sch.symbols}
        assert len(depths) > 1, (
            f"{len(sch.sheet_params)} sheets but every symbol is at one depth "
            f"{depths} — sheet_path filtering is scoping the read")

    # Sheet parameters must actually reach the symbols that reference them.
    unresolved = [s.ref for s in sch.symbols if "${" in s.params]
    assert not unresolved, f"unresolved sheet params: {unresolved[:5]}"

    deck = sch.deck()
    assert ".end" in deck and ".op" in deck
    assert all(f"X{s.ref} " in deck for s in sch.symbols
               if s.model in PORT_SCHEMA and not s.excluded_from_sim), \
        "a known-model symbol is missing from the deck"

    # Net naming must be injective. Two nets collapsing to one name is a short
    # circuit in the deck: it parses, it looks fine, and the operating point
    # becomes unsolvable. giona_fc had 8 of them — every `PDn+`/`PDn-` pair.
    mapped = {raw: sch.net(raw) for s in sch.symbols for p in s.pins
              for raw in (p.net,)}
    inverse: dict[str, str] = {}
    for raw, safe in mapped.items():
        if safe == "0":
            continue
        assert safe not in inverse or inverse[safe] == raw, (
            f"net names collide: {raw!r} and {inverse[safe]!r} both -> {safe!r}")
        inverse[safe] = raw

    # A net name that reached the deck unsanitised would be a parse error.
    for line in deck.splitlines():
        if line.startswith("X"):
            assert "(" not in line and ")" not in line, f"unsanitised net: {line}"

    # Bundle width must be uniform across each Aware instance's optical ports,
    # or the parser refuses the instance — this is what _bundle_widths buys.
    widths = sch._bundle_widths()
    for s in sch.symbols:
        schema = PORT_SCHEMA.get(s.model)
        if schema is None or s.excluded_from_sim:
            continue
        got = {widths.get(sch.net(p.net), 1)
               for kind, p in zip(schema, s.sorted_pins()) if kind == "bundle"}
        assert len(got) <= 1, f"{s.ref}: bundle widths not propagated: {got}"

    # Every electrical primitive must be emitted exactly once, under a name that
    # doesn't double its letter (refdes R1 → "R1", never "RR1").
    names = [ln.split()[0] for ln in deck.splitlines() if ln[:1].isalpha()]
    doubled = [n for n in names if re.match(r"^([A-Za-z])\1", n)]
    assert not doubled, f"doubled primitive letter: {doubled[:5]}"
    assert len(names) == len(set(names)), "duplicate element name in deck"
    for s in sch.symbols:
        if s.primitive and not s.excluded_from_sim and not s.is_power_flag:
            assert s.ref in names, f"{s.ref} ({s.primitive}) missing from deck"

    # Sim.Pins is symbol→model; using it uninverted transposes every source.
    for s in sch.symbols:
        raw = s.fields.get("Sim.Pins", "")
        if s.primitive in _MODEL_NODE_ORDER and raw:
            got = [p.number for p in sch._model_ordered_pins(s, s.primitive)]
            want = [kv.split("=")[0] for node in _MODEL_NODE_ORDER[s.primitive]
                    for kv in raw.split() if kv.endswith("=" + node)]
            assert got == want, f"{s.ref}: Sim.Pins {raw!r} → {got}, expected {want}"

    # A scoped deck must be a subset of the whole, never invent elements.
    if sch.scopes():
        scope = max(sch.scopes(), key=lambda k: -sch.scopes()[k])
        sub = {ln.split()[0] for ln in sch.deck(scope=scope).splitlines()
               if ln[:1].isalpha()}
        assert sub <= set(names), f"scope {scope!r} emitted foreign elements"

    # The deck has to survive the parser it was written for.
    import fairchild
    ckt = fairchild.Circuit()
    ckt.load_str(deck)

    print(sch.report())
    print(f"\n--- deck ({len(deck.splitlines())} lines) ---\n{deck}")
    print(f"demo OK: {len(sch.symbols)} symbols, {total} pins joined to nets, "
          f"deck parses")


if __name__ == "__main__":
    demo()
