[package]
name = "fairchild-py"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Python bindings for the fairchild electro-optic circuit simulator."

[lib]
name = "fairchild"
crate-type = ["cdylib"]

[dependencies]
fairchild-core   = { path = "../fairchild-core" }
fairchild-parser = { path = "../fairchild-parser" }
fairchild-osdi   = { path = "../fairchild-osdi", optional = true }
pyo3             = { version = "0.22", features = ["extension-module"] }
numpy            = "0.22"
rayon            = { workspace = true }

[features]
default = ["osdi"]
osdi = ["dep:fairchild-osdi"]
klu = ["fairchild-core/klu"]
