#!/usr/bin/env bash
# Install the eeschema toolbar buttons into KiCad's user plugin path.
#
# The launcher shims are GENERATED here rather than committed, because they must
# hardcode an absolute path to this checkout's venv: KiCad's own interpreter
# (`api.interpreter_path`) has neither pynng nor the fairchild extension module,
# so a `runtime: "python"` plugin cannot work. `runtime: "exec"` plus a shim
# that calls our venv can.
#
#   ./install.sh [kicad-version]        # default: highest version found
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../../../.." && pwd)"
[ -x "$REPO/.venv/bin/python" ] || { echo "no venv at $REPO/.venv" >&2; exit 1; }

DOCS="$HOME/Documents/KiCad"
[ -d "$DOCS" ] || { echo "no KiCad user dir at $DOCS" >&2; exit 1; }

if [ $# -ge 1 ]; then
    VER="$1"
else
    # Highest version wins, so a dev build beats an old stable one.
    VER="$(ls "$DOCS" | grep -E '^[0-9]+\.[0-9]+$' | sort -t. -k1,1n -k2,2n | tail -1)"
fi
DEST="$DOCS/$VER/plugins/fairchild"
mkdir -p "$DEST"
cp "$HERE/plugin.json" "$DEST/plugin.json"

for action in annotate-op:run clear:clear; do
    verb="${action%%:*}"; file="${action##*:}"
    cat > "$DEST/$file.sh" <<SHIM
#!/bin/sh
# Generated by python/fairchild/kicad/plugin/install.sh — do not edit.
# KiCad exports KICAD_API_SOCKET / KICAD_API_TOKEN into the action's
# environment, so the client needs no socket discovery.
set -eu
export MPLBACKEND=Agg
exec "$REPO/.venv/bin/python" -m fairchild.kicad.button $verb 2>&1
SHIM
    chmod +x "$DEST/$file.sh"
done

echo "installed to $DEST"
echo "restart eeschema to pick up the toolbar buttons"
