/// Modified Nodal Analysis (MNA) matrix assembler.
///
/// Matrix layout (0-based):
///   rows/cols [0 .. n_nodes)          → node voltages (ground excluded)
///   rows/cols [n_nodes .. n_nodes+m)  → voltage-source branch currents
///
/// Ground node "0" is eliminated from the matrix.
use fairchild_parser::{Element, Netlist};
use indexmap::IndexMap;
use std::sync::Arc;

use crate::device::NodeId;
use crate::error::SimError;

/// The topology/index maps for a circuit — built once, reused across time steps.
///
/// Row layout:
///   `[0 .. n_nodes)`             — circuit node voltages
///   `[n_nodes .. n_nodes+n_vsrc)` — voltage-source branch currents
///   `[n_nodes+n_vsrc .. size)`   — device-internal nodes (e.g. OSDI flow
///                                  branches generated by potential
///                                  contributions in Verilog-A models)
#[derive(Clone)]
pub struct CircuitTopology {
    /// Map from node name → matrix row/col (ground excluded).
    pub node_index: IndexMap<String, usize>,
    /// Map from voltage source name → aux current index within A/b.
    pub vsrc_index: IndexMap<String, usize>,
    /// Total matrix dimension = n_nodes + n_vsources + n_device_extras.
    pub size: usize,
}

/// Conductance used to realise an ideal inductor's DC short (S).
///
/// 1 µΩ: three orders above the largest conductance a real circuit presents, so
/// the node pair is effectively tied, and nine orders below 1/f64::EPSILON, so
/// the factorisation stays sound.
const G_DC_SHORT: f64 = 1e6;

impl CircuitTopology {
    pub fn build(netlist: &Netlist) -> CircuitTopology {
        let (node_index, vsrc_index) = index_circuit(netlist);
        let size = node_index.len() + vsrc_index.len();
        CircuitTopology {
            node_index,
            vsrc_index,
            size,
        }
    }

    pub fn n_nodes(&self) -> usize {
        self.node_index.len()
    }

    /// Allocate `n` contiguous MNA rows for device-internal nodes (e.g. OSDI
    /// flow-branch nodes from potential contributions).  Returns the first
    /// allocated index.  Called by `build_devices` once per device that
    /// reports `num_extra_nodes() > 0`.
    pub fn allocate_extra_rows(&mut self, n: usize) -> usize {
        let start = self.size;
        self.size += n;
        start
    }

    /// Add a uniform conductance `g` to the diagonal of every node row
    /// `[0, n_nodes)` and every device-internal row `[vsrc_end, size)`, skipping
    /// the voltage-source branch rows `[n_nodes, vsrc_end)` — those carry their
    /// own KCL equation and must keep a clean diagonal.
    ///
    /// This is the single source of truth for the gmin floor applied identically
    /// by DC/Newton, transient, AC, and noise assembly. Callers pass the value
    /// they want stamped: `opts.gmin` for the steady floor, or
    /// `opts.gmin + gmin_extra` during gmin-stepping homotopy. The internal-row
    /// floor is what keeps degenerate OSDI/optical potential rows non-singular;
    /// the deliberate divergence from ngspice (which applies gmin across
    /// junctions only) is discussed in `_notes/sotu.md §E`.
    ///
    /// Operates on any row-major dense matrix (`mat.a`, the AC/noise real
    /// `g_mat`, or a condition-estimate copy).
    /// Generic over the row type so one implementation serves both the sparse
    /// [`SparseRow`] matrix the Newton loop stamps and the dense `Vec<f64>`
    /// rows `.ac`/`.noise` build for their complex assembly.
    pub fn stamp_gmin<R>(&self, a: &mut [R], g: f64)
    where
        R: std::ops::IndexMut<usize, Output = f64>,
    {
        let n_nodes = self.n_nodes();
        for (i, row) in a.iter_mut().enumerate().take(n_nodes) {
            row[i] += g;
        }
        let vsrc_end = n_nodes + self.vsrc_index.len();
        for (i, row) in a.iter_mut().enumerate().skip(vsrc_end) {
            row[i] += g;
        }
    }

    /// Compressed-sparse-column arrays `(ap, ai, ax)` built straight from the
    /// sparse rows, dropping values at or below `thr`.
    ///
    /// This is what a sparse LU backend actually wants, and building it from
    /// the row structure is O(nnz). The dense equivalent
    /// (`fairchild_klu::dense_to_csc`) scanned all n² cells in column-major
    /// order over row-major storage — 41 ms per call at n = 3200.
    pub fn to_csc(a: &[SparseRow], thr: f64) -> (Vec<i32>, Vec<i32>, Vec<f64>) {
        let n = a.len();
        let mut col_count = vec![0i32; n];
        for row in a {
            for (j, v) in row.iter() {
                if v.abs() > thr {
                    col_count[j] += 1;
                }
            }
        }
        let mut ap = vec![0i32; n + 1];
        for j in 0..n {
            ap[j + 1] = ap[j] + col_count[j];
        }
        let nnz = ap[n] as usize;
        let mut ai = vec![0i32; nnz];
        let mut ax = vec![0.0f64; nnz];
        let mut fill = ap.clone();
        // Row-major walk keeps row indices ascending within each column.
        for (i, row) in a.iter().enumerate() {
            for (j, v) in row.iter() {
                if v.abs() > thr {
                    let k = fill[j] as usize;
                    ai[k] = i as i32;
                    ax[k] = v;
                    fill[j] += 1;
                }
            }
        }
        (ap, ai, ax)
    }

    /// Wrap dense rows as sparse ones, dropping exact zeros.
    ///
    /// ponytail: exists only to bridge the still-dense `.ac`/`.noise` assembly
    /// to the sparse solver interface. Delete it when those assemble sparse
    /// rows directly (task #12) — nothing else should need it.
    ///
    /// For the `.ac` / `.noise` assemblies, which still build their real
    /// 2n×2n complex-as-real system densely. They allocate three dense n×n
    /// matrices already, so this conversion changes nothing asymptotically —
    /// sparsifying those assemblies is its own piece of work.
    pub fn sparse_from_dense(a: &[Vec<f64>]) -> Vec<SparseRow> {
        a.iter()
            .map(|row| {
                SparseRow::from_sorted_cells(
                    row.iter()
                        .enumerate()
                        .filter(|(_, v)| **v != 0.0)
                        .map(|(j, &v)| (j as u32, v))
                        .collect(),
                )
            })
            .collect()
    }

    /// Materialise sparse rows as a dense row-major matrix.
    ///
    /// For the paths that are inherently O(n²) anyway — dense LU, the
    /// condition-number estimate, and the one-shot `klu_solve_dense`. Never
    /// call it from a Newton iteration.
    ///
    /// ponytail: dense LU is O(n³) and the condition estimate is a diagnostic,
    /// so materialising for them is not a corner being cut — it is the right
    /// representation for those two. This is not on the task-#12 list.
    pub fn to_dense(a: &[SparseRow], n: usize) -> Vec<Vec<f64>> {
        let mut d = vec![vec![0.0f64; n]; n];
        for (i, row) in a.iter().enumerate() {
            for (j, v) in row.iter() {
                d[i][j] = v;
            }
        }
        d
    }

    /// Retrieve a node voltage from a solution vector.
    pub fn node_voltage(&self, node: &str, x: &[f64]) -> Result<f64, SimError> {
        if node == "0" || node == "gnd" {
            return Ok(0.0);
        }
        self.node_index
            .get(node)
            .map(|&i| x[i])
            .ok_or_else(|| SimError::UnknownNode(node.to_string()))
    }

    /// Retrieve a voltage-source branch current from a solution vector.
    pub fn vsrc_current(&self, vsrc_name: &str, x: &[f64]) -> Result<f64, SimError> {
        self.vsrc_index
            .get(vsrc_name)
            .map(|&i| x[self.n_nodes() + i])
            .ok_or_else(|| SimError::UnknownNode(vsrc_name.to_string()))
    }
}

// ---------------------------------------------------------------------------
// Structural sparsity pattern
// ---------------------------------------------------------------------------

/// The set of `(row, col)` cells any stamper may write, stored row-major to
/// mirror `MnaMatrix::a`.
///
/// A circuit matrix is ~0.1 % occupied, so the two full-matrix passes per
/// Newton iteration — zeroing it, then scanning it to build the solver's CSC —
/// cost O(n²) against O(nnz) of real work.  At n ≈ 3000 that was ~90 % of solve
/// time with the numeric LU itself at ~1 %.  The pattern is also what
/// [`SparseRow`] allocates against, so the storage itself is O(nnz).
/// Knowing the footprint up front turns both passes into O(nnz).
///
/// This is a *superset*: it is built structurally, from each element's
/// terminals and each device's terminals + bound extra rows, without regard to
/// whether a given cell happens to be non-zero at the current operating point.
/// That matters — a cell that is zero at x=0 and non-zero at the solution must
/// still be in the pattern, and value-based discovery on the first iteration
/// would miss exactly those (photonic devices stamp such cells; see the WDM DC
/// OP regression).  Consumers that want the tight numeric set (the sparse
/// solver) narrow it themselves and can detect growth in O(nnz).
#[derive(Debug, Clone)]
pub struct Pattern {
    /// Column indices per row, sorted and deduplicated.
    pub cols: Vec<Vec<u32>>,
    /// Total cell count — the `nnz` upper bound.
    pub nnz: usize,
}

/// What structural footprint one device contributes to [`Pattern`].
///
/// A device that only reports the rows it owns gets the conservative clique;
/// one that implements [`crate::device::Device::stamp_pairs`] declares the
/// cells it actually touches, which matters once a device owns enough rows for
/// `O(rows²)` to hurt. See that method for the numbers.
#[derive(Clone, Debug)]
pub enum Footprint {
    /// Every ordered pair drawn from these rows.
    Clique(Vec<usize>),
    /// Exactly these `(row, col)` cells.
    Pairs(Vec<(usize, usize)>),
}

impl Pattern {
    /// Structural footprint of a netlist plus its device instances.
    ///
    /// `device_nodes[k]` is device `k`'s footprint: either every MNA row/column
    /// it may touch (its resolved terminals plus any extra rows it was bound),
    /// which becomes a clique, or the exact cells it declared.  Devices only
    /// ever stamp within their footprint (verified in debug builds by
    /// [`MnaMatrix::debug_assert_covers`]), except for those that report more
    /// via [`crate::device::Device::extra_stamp_rows`].
    pub fn build(topo: &CircuitTopology, netlist: &Netlist, device_nodes: &[Footprint]) -> Pattern {
        let n = topo.size;
        let mut b = PatternBuilder::new(n);
        // `stamp_gmin` floors the diagonal, and a structurally present diagonal
        // is what sparse LU wants anyway.
        for i in 0..n {
            b.touch(i, i);
        }
        let idx = |name: &str| topo.node_index.get(name).copied();
        let n_nodes = topo.n_nodes();
        for el in &netlist.elements {
            match el {
                Element::Resistor { pos, neg, .. }
                | Element::Capacitor { pos, neg, .. }
                | Element::Inductor { pos, neg, .. } => {
                    b.clique(&[idx(pos), idx(neg)]);
                }
                Element::CoupledInductors { l1, l2, .. } => {
                    let (p1, n1) = find_inductor_terminals(netlist, l1);
                    let (p2, n2) = find_inductor_terminals(netlist, l2);
                    b.clique(&[idx(p1), idx(n1), idx(p2), idx(n2)]);
                }
                Element::VoltageSource { name, pos, neg, .. } => {
                    let vi = topo.vsrc_index.get(name).map(|&i| n_nodes + i);
                    b.clique(&[idx(pos), idx(neg), vi]);
                }
                // Current sources touch b only; devices are handled below.
                _ => {}
            }
        }
        for foot in device_nodes {
            match foot {
                Footprint::Clique(nodes) => {
                    let ids: Vec<Option<usize>> = nodes.iter().map(|&i| Some(i)).collect();
                    b.clique(&ids);
                }
                Footprint::Pairs(pairs) => {
                    for &(r, c) in pairs {
                        b.touch(r, c);
                    }
                }
            }
        }
        b.finish()
    }
}

/// Accumulator for [`Pattern::build`].
struct PatternBuilder {
    cols: Vec<Vec<u32>>,
}

impl PatternBuilder {
    fn new(size: usize) -> Self {
        PatternBuilder {
            cols: vec![Vec::new(); size],
        }
    }

    fn touch(&mut self, i: usize, j: usize) {
        self.cols[i].push(j as u32);
    }

    /// Mark every ordered pair drawn from `nodes` (ground entries skipped).  A
    /// stamper handed a set of rows can couple any of them to any other, so the
    /// clique is the tightest footprint derivable without asking the stamper.
    fn clique(&mut self, nodes: &[Option<usize>]) {
        for &i in nodes.iter().flatten() {
            for &j in nodes.iter().flatten() {
                self.touch(i, j);
            }
        }
    }

    fn finish(mut self) -> Pattern {
        let mut nnz = 0;
        for row in self.cols.iter_mut() {
            row.sort_unstable();
            row.dedup();
            row.shrink_to_fit();
            nnz += row.len();
        }
        Pattern {
            cols: self.cols,
            nnz,
        }
    }
}

/// One row of the MNA matrix, stored sparse but indexed as though dense.
///
/// # Why this exists in this shape
///
/// Every device in the tree stamps through `mat.a[i][j] += v`. A circuit matrix
/// is ~0.1 % occupied, so `Vec<Vec<f64>>` allocated and zeroed an n² array —
/// 82 MB at n = 3200 — to hold a few thousand numbers, and that allocation was
/// the last O(n²) left in the solver once `Pattern` had made clearing and
/// scanning O(nnz).
///
/// Implementing `Index`/`IndexMut` over a sorted column list keeps `a[i][j]`
/// compiling untouched in all ~20 device stampers while the storage underneath
/// becomes O(nnz). The cost is a binary search per stamp instead of a direct
/// offset; rows carry a handful of entries, so that is 2-3 comparisons.
///
/// A read of an absent cell yields `0.0`, as a dense matrix would. A *write* to
/// an absent cell inserts it, which keeps patternless matrices (unit tests,
/// `MnaMatrix::zeros`) working; with a pattern attached every cell a stamper
/// can touch is pre-allocated, so no insertion ever happens on the hot path.
#[derive(Clone, Debug, Default)]
pub struct SparseRow {
    /// Column indices, sorted ascending.
    cols: Vec<u32>,
    /// Values, parallel to `cols`.
    vals: Vec<f64>,
}

/// Returned for reads of cells that are structurally absent.
static ZERO: f64 = 0.0;

impl SparseRow {
    /// A row with every column of `cols` pre-allocated at zero.
    fn with_cols(cols: &[u32]) -> Self {
        SparseRow {
            cols: cols.to_vec(),
            vals: vec![0.0; cols.len()],
        }
    }

    /// Build from `(column, value)` cells. Sorts, so callers may emit in any
    /// order; used by the sparse transpose in `crate::solver`.
    pub fn from_sorted_cells(mut cells: Vec<(u32, f64)>) -> Self {
        cells.sort_unstable_by_key(|&(j, _)| j);
        let mut cols = Vec::with_capacity(cells.len());
        let mut vals = Vec::with_capacity(cells.len());
        for (j, v) in cells {
            cols.push(j);
            vals.push(v);
        }
        SparseRow { cols, vals }
    }

    /// Non-zero `(column, value)` pairs, ascending by column.
    pub fn iter(&self) -> impl Iterator<Item = (usize, f64)> + '_ {
        self.cols
            .iter()
            .zip(self.vals.iter())
            .map(|(&j, &v)| (j as usize, v))
    }

    /// Every allocated `(column, value)` pair including explicit zeros —
    /// the storage order the solvers walk.
    pub fn entries(&self) -> (&[u32], &[f64]) {
        (&self.cols, &self.vals)
    }

    /// Set every allocated value to zero, keeping the column structure so the
    /// next stamp needs no insertion.
    fn clear(&mut self) {
        self.vals.fill(0.0);
    }

    fn slot(&self, j: usize) -> Result<usize, usize> {
        self.cols.binary_search(&(j as u32))
    }
}

impl std::ops::Index<usize> for SparseRow {
    type Output = f64;
    fn index(&self, j: usize) -> &f64 {
        match self.slot(j) {
            Ok(k) => &self.vals[k],
            Err(_) => &ZERO,
        }
    }
}

impl std::ops::IndexMut<usize> for SparseRow {
    fn index_mut(&mut self, j: usize) -> &mut f64 {
        match self.slot(j) {
            Ok(k) => &mut self.vals[k],
            Err(k) => {
                // Only reachable on a patternless matrix; with a pattern every
                // stampable cell is pre-allocated.
                self.cols.insert(k, j as u32);
                self.vals.insert(k, 0.0);
                &mut self.vals[k]
            }
        }
    }
}

/// An assembled MNA system: A·x = b.
pub struct MnaMatrix {
    pub a: Vec<SparseRow>,
    pub b: Vec<f64>,
    /// Structural footprint, when the caller built one.  Present only on the
    /// matrices owned by the hot NR / transient loops; `None` keeps the
    /// original dense behaviour for one-shot and diagnostic stamps.
    pattern: Option<Arc<Pattern>>,
}

impl MnaMatrix {
    fn new(size: usize) -> Self {
        MnaMatrix {
            // Patternless: rows grow on first write. Only unit tests and the
            // one-shot diagnostic stamps land here.
            a: vec![SparseRow::default(); size],
            b: vec![0.0f64; size],
            pattern: None,
        }
    }

    /// Build a zero-filled MnaMatrix at the given dimension.  Useful for
    /// diagnostic passes that need a clean scratch matrix without going
    /// through the netlist stamper.
    pub fn zeros(size: usize) -> Self {
        Self::new(size)
    }

    /// Zero-filled, carrying a structural [`Pattern`] so `clear` and
    /// `residual_norm` run at O(nnz) instead of O(n²).
    pub fn with_pattern(size: usize, pattern: Arc<Pattern>) -> Self {
        assert_eq!(
            pattern.cols.len(),
            size,
            "pattern built at a different size"
        );
        let a = pattern
            .cols
            .iter()
            .map(|cols| SparseRow::with_cols(cols))
            .collect();
        MnaMatrix {
            a,
            b: vec![0.0f64; size],
            pattern: Some(pattern),
        }
    }

    pub fn pattern(&self) -> Option<&Arc<Pattern>> {
        self.pattern.as_ref()
    }

    /// Zero every cell of `a` and every entry of `b` in place.  Used by
    /// the hot NR / transient loops to reuse a single `MnaMatrix`
    /// allocation across iterations instead of paying N+1 heap
    /// allocations per stamp.
    ///
    /// With a pattern attached, only cells inside it are touched — sound
    /// because the pattern is a superset of what any stamper writes, so
    /// everything outside it is already zero and stays zero.
    pub fn clear(&mut self) {
        // Sparse rows keep their column structure, so this is O(nnz) whether or
        // not a pattern is attached — and the next stamp needs no insertion.
        for row in self.a.iter_mut() {
            row.clear();
        }
        self.b.fill(0.0);
    }

    /// ‖A·x − b‖₂ for the currently stamped system.
    ///
    /// This is the Newton residual norm the Armijo line search compares.  The
    /// caller must not re-stamp to get it: whatever `A` and `b` hold right now
    /// is the linearisation at whichever `x` was last stamped.
    pub fn residual_norm(&self, x: &[f64]) -> f64 {
        let mut sumsq = 0.0_f64;
        // O(nnz) by construction now — the row *is* its own sparsity pattern,
        // so this needs no separate `pattern` branch.
        for (i, row) in self.a.iter().enumerate() {
            let (cols, vals) = row.entries();
            let mut acc = 0.0_f64;
            for (&j, &v) in cols.iter().zip(vals.iter()) {
                acc += v * x[j as usize];
            }
            let f = acc - self.b[i];
            sumsq += f * f;
        }
        sumsq.sqrt()
    }

    /// Debug-only check that the attached pattern really covers every non-zero
    /// in `a`.  A miss means some stamper wrote outside the footprint derived
    /// from its terminals, which would silently drop that entry from the sparse
    /// solve — so this guards the one invariant the whole scheme rests on.
    /// Called once per NR loop after the first stamp; O(nnz), debug builds only.
    /// A stamper writing outside the pattern now *inserts* the cell rather than
    /// silently filling a dense slot, so this catches it either way.
    pub fn debug_assert_covers(&self) {
        let Some(p) = &self.pattern else { return };
        for (i, row) in self.a.iter().enumerate() {
            for (j, v) in row.iter() {
                if v != 0.0 && p.cols[i].binary_search(&(j as u32)).is_err() {
                    panic!(
                        "sparsity pattern misses a stamped cell at ({i}, {j}) = {v}; \
                         a device stamped outside its terminals + extra rows without \
                         reporting them via Device::extra_stamp_rows"
                    );
                }
            }
        }
    }
}

/// Per-circuit stamping plan: everything about `(topo, netlist)` that the
/// element stamper would otherwise recompute on every Newton iteration.
///
/// Built once by each NR / transient loop.  Two things live here: the resolved
/// node indices (the stamper hashed element node *names* into `node_index` on
/// every pass — ~8 % of runtime on a large ladder), and the structural
/// [`Pattern`].
pub struct StampPlan {
    /// `(pos, neg)` resolved MNA indices, one entry per element in
    /// `netlist.elements` order.  `None` = ground or unknown.
    elem_nodes: Vec<(NodeId, NodeId)>,
    /// Voltage-source aux row per element (only set for `VoltageSource`).
    elem_vi: Vec<Option<usize>>,
    /// Whether the netlist has any coupled inductors.  When it doesn't — the
    /// overwhelmingly common case — the stamper skips building two name-keyed
    /// maps (with `String` clones) on every pass.
    has_coupled: bool,
    pub pattern: Arc<Pattern>,
}

impl StampPlan {
    pub fn new(topo: &CircuitTopology, netlist: &Netlist, device_nodes: &[Footprint]) -> StampPlan {
        let n_nodes = topo.n_nodes();
        let mut elem_nodes = Vec::with_capacity(netlist.elements.len());
        let mut elem_vi = Vec::with_capacity(netlist.elements.len());
        for el in &netlist.elements {
            let (pos, neg) = match el {
                Element::Resistor { pos, neg, .. }
                | Element::Capacitor { pos, neg, .. }
                | Element::Inductor { pos, neg, .. }
                | Element::VoltageSource { pos, neg, .. }
                | Element::CurrentSource { pos, neg, .. } => (
                    topo.node_index.get(pos).copied(),
                    topo.node_index.get(neg).copied(),
                ),
                _ => (None, None),
            };
            elem_nodes.push((pos, neg));
            elem_vi.push(match el {
                Element::VoltageSource { name, .. } => {
                    topo.vsrc_index.get(name).map(|&i| n_nodes + i)
                }
                _ => None,
            });
        }
        StampPlan {
            elem_nodes,
            elem_vi,
            has_coupled: netlist
                .elements
                .iter()
                .any(|e| matches!(e, Element::CoupledInductors { .. })),
            pattern: Arc::new(Pattern::build(topo, netlist, device_nodes)),
        }
    }
}

// ---------------------------------------------------------------------------
// DC stamp (time-independent elements, or companion equivalents for C/L)
// ---------------------------------------------------------------------------

/// In-place version of [`stamp_netlist_scaled`].  `mat` is cleared and
/// then filled — the caller owns the allocation and reuses it across NR
/// iterations to avoid the N+1 heap allocations per stamp.
pub fn stamp_netlist_scaled_in_place(
    mat: &mut MnaMatrix,
    topo: &CircuitTopology,
    netlist: &Netlist,
    source_scale: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
    plan: Option<&StampPlan>,
) {
    stamp_netlist_in_place(mat, topo, netlist, 0.0, cap_state, ind_state, plan);
    if (source_scale - 1.0).abs() < 1e-15 {
        return;
    }
    let n_nodes = topo.n_nodes();
    for (name, &vi_idx) in &topo.vsrc_index {
        let vi = n_nodes + vi_idx;
        if let Some(Element::VoltageSource { waveform, .. }) = netlist
            .elements
            .iter()
            .find(|e| matches!(e, Element::VoltageSource { name: n, .. } if n == name))
        {
            let v_full = waveform.at(0.0);
            mat.b[vi] = mat.b[vi] - v_full + v_full * source_scale;
        }
    }
    for el in &netlist.elements {
        if let Element::CurrentSource {
            pos, neg, waveform, ..
        } = el
        {
            let i_full = waveform.at(0.0);
            if i_full == 0.0 {
                continue;
            }
            let delta = i_full * (source_scale - 1.0);
            if let Some(&p) = topo.node_index.get(pos) {
                mat.b[p] -= delta;
            }
            if let Some(&n) = topo.node_index.get(neg) {
                mat.b[n] += delta;
            }
        }
    }
}

/// Allocating variant: produces a fresh `MnaMatrix`.  Kept for non-hot
/// call sites (one-off diagnostics, AC side-car G assembly).  The NR
/// inner loops should call [`stamp_netlist_scaled_in_place`] against a
/// reused matrix instead.
pub fn stamp_netlist_scaled(
    topo: &CircuitTopology,
    netlist: &Netlist,
    source_scale: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
) -> MnaMatrix {
    let mut mat = stamp_netlist(topo, netlist, 0.0, cap_state, ind_state);
    if (source_scale - 1.0).abs() < 1e-15 {
        return mat;
    }
    // Re-scale source contributions: voltage sources stamp into b[vi], current sources into b[node].
    // Rather than re-stamping from scratch, rescale: b[vi] already has waveform.at(0) from
    // stamp_netlist (t=0 = DC value). We just scale b entries for source rows.
    let n_nodes = topo.n_nodes();
    for (name, &vi_idx) in &topo.vsrc_index {
        let vi = n_nodes + vi_idx;
        // Find the source's waveform value and rescale.
        if let Some(Element::VoltageSource { waveform, .. }) = netlist
            .elements
            .iter()
            .find(|e| matches!(e, Element::VoltageSource { name: n, .. } if n == name))
        {
            let v_full = waveform.at(0.0);
            // The stamp put v_full into b[vi]; replace with v_full * source_scale.
            mat.b[vi] = mat.b[vi] - v_full + v_full * source_scale;
        }
    }
    for el in &netlist.elements {
        if let Element::CurrentSource {
            pos, neg, waveform, ..
        } = el
        {
            let i_full = waveform.at(0.0);
            if i_full == 0.0 {
                continue;
            }
            let delta = i_full * (source_scale - 1.0);
            // stamp_current_source: b[pos] -= i, b[neg] += i. Scale correction = delta.
            if let Some(&p) = topo.node_index.get(pos) {
                mat.b[p] -= delta;
            }
            if let Some(&n) = topo.node_index.get(neg) {
                mat.b[n] += delta;
            }
        }
    }
    mat
}

/// In-place stamp.  Clears `mat` then fills the full MNA system.  The
/// caller owns the allocation — used by the NR / transient inner loops
/// to skip per-iteration heap allocation.
pub fn stamp_netlist_in_place(
    mat: &mut MnaMatrix,
    topo: &CircuitTopology,
    netlist: &Netlist,
    t: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
    plan: Option<&StampPlan>,
) {
    mat.clear();
    stamp_netlist_into(mat, topo, netlist, t, cap_state, ind_state, plan);
}

/// Allocating variant: produces a fresh `MnaMatrix`.  Kept for non-hot
/// callers (DC OP one-shots, AC G-matrix assembly, diagnostic dumps).
///
/// `t`           — current simulation time (used for PULSE sources)
/// `cap_state`   — map from capacitor name → (G_eq, I_hist) BE companion pair
/// `ind_state`   — map from inductor name  → (G_eq, I_hist) BE companion pair
pub fn stamp_netlist(
    topo: &CircuitTopology,
    netlist: &Netlist,
    t: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
) -> MnaMatrix {
    let mut mat = MnaMatrix::new(topo.size);
    stamp_netlist_into(&mut mat, topo, netlist, t, cap_state, ind_state, None);
    mat
}

/// Internal shared stamping body.  Assumes `mat` is already zeroed at
/// the right size (caller responsibility).
fn stamp_netlist_into(
    mat: &mut MnaMatrix,
    topo: &CircuitTopology,
    netlist: &Netlist,
    t: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
    plan: Option<&StampPlan>,
) {
    use std::collections::HashMap;

    let n_nodes = topo.n_nodes();

    // Build coupled-inductor map: inductor_name → (partner_name, coupling_k)
    // and a value map for inductance lookups.  Skipped outright when the
    // netlist has no coupled inductors: it is two allocations plus a `String`
    // clone per inductor, on a path that runs every Newton iteration.
    let mut coupled_map: HashMap<String, (String, f64)> = HashMap::new();
    let mut ind_values: HashMap<String, f64> = HashMap::new();
    if plan.is_none_or(|p| p.has_coupled) {
        for el in &netlist.elements {
            if let Element::Inductor {
                name, inductance, ..
            } = el
            {
                ind_values.insert(name.clone(), *inductance);
            }
            if let Element::CoupledInductors {
                l1, l2, coupling, ..
            } = el
            {
                coupled_map.insert(l1.clone(), (l2.clone(), *coupling));
                coupled_map.insert(l2.clone(), (l1.clone(), *coupling));
            }
        }
    }

    for (ei, el) in netlist.elements.iter().enumerate() {
        // Pre-resolved terminals when the caller built a plan; otherwise hash
        // the node names as before.
        let resolved = plan.map(|p| p.elem_nodes[ei]);
        match el {
            Element::Resistor {
                pos,
                neg,
                resistance,
                ..
            } => {
                let (p, n) = resolved.unwrap_or_else(|| {
                    (
                        topo.node_index.get(pos).copied(),
                        topo.node_index.get(neg).copied(),
                    )
                });
                stamp_conductance_at(&mut mat.a, p, n, 1.0 / resistance);
            }
            Element::Capacitor { name, pos, neg, .. } => {
                if let Some(&(g_eq, i_hist)) = cap_state.get(name) {
                    let (p, n) = resolved.unwrap_or_else(|| {
                        (
                            topo.node_index.get(pos).copied(),
                            topo.node_index.get(neg).copied(),
                        )
                    });
                    stamp_conductance_at(&mut mat.a, p, n, g_eq);
                    // BE companion: KCL at pos gives b[pos] += I_hist.
                    // stamp_current_source(neg, pos, v) adds v to b[pos].
                    stamp_current_source_at(&mut mat.b, n, p, i_hist);
                }
                // Capacitor absent from cap_state = open circuit (correct for DC OP).
            }
            Element::Inductor { name, pos, neg, .. } => {
                if let Some(&(g_eq, i_hist)) = ind_state.get(name) {
                    let (p, n) = resolved.unwrap_or_else(|| {
                        (
                            topo.node_index.get(pos).copied(),
                            topo.node_index.get(neg).copied(),
                        )
                    });
                    // For coupled inductors, skip the standalone self-conductance stamp;
                    // the CoupledInductors arm below handles the full 2×2 companion.
                    if !coupled_map.contains_key(name) {
                        stamp_conductance_at(&mut mat.a, p, n, g_eq);
                    }
                    // Always stamp history current source.
                    stamp_current_source_at(&mut mat.b, p, n, i_hist);
                } else {
                    // No companion state means this is a DC solve, and at DC an
                    // ideal inductor is a SHORT — the dual of the capacitor's
                    // open above. It used to be left open, which silently cut
                    // every DC path through an inductor: a source feeding a load
                    // through a choke or a bondwire read 0 V, and a *current*
                    // source into one left its node with nothing but gmin on the
                    // diagonal, so the first Newton step demanded I/gmin volts
                    // (1e9 V for 1 mA). On giona_fc that collapsed the vmax trust
                    // region and took every optical phase with it.
                    //
                    // Enforced as a large conductance rather than a branch
                    // constraint because a branch row would change topo.size, and
                    // the sparsity pattern / symbolic LU cache are built from it.
                    // G_DC_SHORT is far above any physical circuit conductance and
                    // far below 1/eps, so the node pair is tied without wrecking
                    // the conditioning.
                    let (p, n) = resolved.unwrap_or_else(|| {
                        (
                            topo.node_index.get(pos).copied(),
                            topo.node_index.get(neg).copied(),
                        )
                    });
                    stamp_conductance_at(&mut mat.a, p, n, G_DC_SHORT);
                }
            }
            Element::CoupledInductors {
                l1, l2, coupling, ..
            } => {
                // Both inductors must be in ind_state (transient); skip at DC.
                let Some(&(g_eq1, _)) = ind_state.get(l1) else {
                    continue;
                };
                let Some(&(g_eq2, _)) = ind_state.get(l2) else {
                    continue;
                };
                let Some(&val1) = ind_values.get(l1) else {
                    continue;
                };
                let Some(&val2) = ind_values.get(l2) else {
                    continue;
                };
                let k = *coupling;
                let m = k * (val1 * val2).sqrt();
                let det = val1 * val2 - m * m; // = val1*val2*(1-k²)
                if det.abs() < 1e-40 {
                    continue;
                } // k≈1: degenerate, skip
                  // Extract h from g_eq = h/L  =>  h = g_eq * L
                let h = g_eq1 * val1;
                let g11 = h * val2 / det;
                let g22 = h * val1 / det;
                let g12 = -h * m / det;

                let (pos1, neg1) = find_inductor_terminals(netlist, l1);
                let (pos2, neg2) = find_inductor_terminals(netlist, l2);

                stamp_conductance(&mut mat.a, &topo.node_index, pos1, neg1, g11);
                stamp_conductance(&mut mat.a, &topo.node_index, pos2, neg2, g22);
                stamp_mutual_conductance(&mut mat.a, &topo.node_index, pos1, neg1, pos2, neg2, g12);

                // Verify g_eq2-derived h is consistent (both inductors share same step).
                let _ = g_eq2; // used above implicitly; avoid unused variable warning
            }
            Element::VoltageSource {
                name,
                pos,
                neg,
                waveform,
                ..
            } => {
                let (p, n) = resolved.unwrap_or_else(|| {
                    (
                        topo.node_index.get(pos).copied(),
                        topo.node_index.get(neg).copied(),
                    )
                });
                let vi = match plan.and_then(|pl| pl.elem_vi[ei]) {
                    Some(vi) => vi,
                    None => n_nodes + topo.vsrc_index[name],
                };
                stamp_vsource_at(&mut mat.a, &mut mat.b, p, n, vi, waveform.at(t));
            }
            Element::CurrentSource {
                pos, neg, waveform, ..
            } => {
                // SPICE: current flows from n+ through source to n- → subtract from n+, add to n-.
                let (p, n) = resolved.unwrap_or_else(|| {
                    (
                        topo.node_index.get(pos).copied(),
                        topo.node_index.get(neg).copied(),
                    )
                });
                stamp_current_source_at(&mut mat.b, p, n, waveform.at(t));
            }
            Element::Diode { .. }
            | Element::Mosfet { .. }
            | Element::Bjt { .. }
            | Element::XOsdi { .. }
            | Element::Behavioral { .. }
            | Element::TransmissionLine { .. }
            | Element::VoltageSwitch { .. }
            | Element::CurrentSwitch { .. } => {
                // Stamped by the Device trait inside the Newton-Raphson loop
                // (the T-line carries time-dependent history sources; a switch's
                // conductance depends on the solution).
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Stamp primitives
// ---------------------------------------------------------------------------

/// Add a conductance G between pos and neg (same as resistor with R=1/G).
pub fn stamp_conductance(
    a: &mut [SparseRow],
    idx: &IndexMap<String, usize>,
    pos: &str,
    neg: &str,
    g: f64,
) {
    stamp_conductance_at(a, idx.get(pos).copied(), idx.get(neg).copied(), g);
}

/// [`stamp_conductance`] against pre-resolved row indices.  `None` = ground.
pub fn stamp_conductance_at(a: &mut [SparseRow], pos: NodeId, neg: NodeId, g: f64) {
    if let Some(p) = pos {
        a[p][p] += g;
        if let Some(n) = neg {
            a[p][n] -= g;
            a[n][p] -= g;
        }
    }
    if let Some(n) = neg {
        a[n][n] += g;
    }
}

/// Stamp a voltage source at aux row `vi`: V(pos) - V(neg) = value.
fn stamp_vsource_at(
    a: &mut [SparseRow],
    b: &mut [f64],
    pos: NodeId,
    neg: NodeId,
    vi: usize,
    value: f64,
) {
    if let Some(p) = pos {
        a[p][vi] += 1.0;
        a[vi][p] += 1.0;
    }
    if let Some(n) = neg {
        a[n][vi] -= 1.0;
        a[vi][n] -= 1.0;
    }
    b[vi] += value;
}

/// Stamp a current source.
/// SPICE convention: positive current flows from pos through source to neg.
///   → b[pos] -= value,  b[neg] += value
fn stamp_current_source_at(b: &mut [f64], pos: NodeId, neg: NodeId, value: f64) {
    if let Some(p) = pos {
        b[p] -= value;
    }
    if let Some(n) = neg {
        b[n] += value;
    }
}

// ---------------------------------------------------------------------------
// Index builder
// ---------------------------------------------------------------------------

fn index_circuit(netlist: &Netlist) -> (IndexMap<String, usize>, IndexMap<String, usize>) {
    let mut node_index: IndexMap<String, usize> = IndexMap::new();
    let mut vsrc_index: IndexMap<String, usize> = IndexMap::new();

    for el in &netlist.elements {
        match el {
            Element::Resistor { pos, neg, .. }
            | Element::Capacitor { pos, neg, .. }
            | Element::Inductor { pos, neg, .. }
            | Element::CurrentSource { pos, neg, .. } => {
                add_node(&mut node_index, pos);
                add_node(&mut node_index, neg);
            }
            Element::Diode { anode, cathode, .. } => {
                add_node(&mut node_index, anode);
                add_node(&mut node_index, cathode);
            }
            Element::Mosfet {
                drain,
                gate,
                source,
                bulk,
                ..
            } => {
                add_node(&mut node_index, drain);
                add_node(&mut node_index, gate);
                add_node(&mut node_index, source);
                add_node(&mut node_index, bulk);
            }
            Element::Bjt {
                collector,
                base,
                emitter,
                substrate,
                ..
            } => {
                add_node(&mut node_index, collector);
                add_node(&mut node_index, base);
                add_node(&mut node_index, emitter);
                add_node(&mut node_index, substrate);
            }
            Element::VoltageSource { name, pos, neg, .. } => {
                add_node(&mut node_index, pos);
                add_node(&mut node_index, neg);
                let n = vsrc_index.len();
                vsrc_index.entry(name.clone()).or_insert(n);
            }
            Element::XOsdi { nets, .. } => {
                for net in nets {
                    add_node(&mut node_index, net);
                }
            }
            Element::Behavioral {
                name,
                pos,
                neg,
                kind,
                ..
            } => {
                add_node(&mut node_index, pos);
                add_node(&mut node_index, neg);
                if *kind == fairchild_parser::BehavioralKind::Voltage {
                    let n = vsrc_index.len();
                    vsrc_index.entry(name.clone()).or_insert(n);
                }
            }
            Element::CoupledInductors { .. } => {
                // No new nodes — L1 and L2 terminals already registered by their
                // Inductor elements.
            }
            Element::VoltageSwitch {
                pos,
                neg,
                ctrl_pos,
                ctrl_neg,
                ..
            } => {
                add_node(&mut node_index, pos);
                add_node(&mut node_index, neg);
                add_node(&mut node_index, ctrl_pos);
                add_node(&mut node_index, ctrl_neg);
            }
            Element::CurrentSwitch { pos, neg, .. } => {
                // The control is a voltage source's branch row, which that
                // source already registered — no node of its own.
                add_node(&mut node_index, pos);
                add_node(&mut node_index, neg);
            }
            Element::TransmissionLine {
                a_pos,
                a_neg,
                b_pos,
                b_neg,
                ..
            } => {
                add_node(&mut node_index, a_pos);
                add_node(&mut node_index, a_neg);
                add_node(&mut node_index, b_pos);
                add_node(&mut node_index, b_neg);
                // The two branch-current rows are device extra nodes, allocated
                // by build_devices via num_extra_nodes/bind_extra_nodes.
            }
        }
    }

    (node_index, vsrc_index)
}

fn add_node(map: &mut IndexMap<String, usize>, node: &str) {
    if node != "0" {
        let n = map.len();
        map.entry(node.to_string()).or_insert(n);
    }
}

/// Backward Euler companion state for a capacitor at one time step.
/// Returns (G_eq, I_hist) where G_eq = C/h and I_hist = G_eq * V_prev.
pub fn cap_companion(capacitance: f64, h: f64, v_prev: f64) -> (f64, f64) {
    let g = capacitance / h;
    (g, g * v_prev)
}

/// Backward Euler companion state for an inductor at one time step.
/// Returns (G_eq, I_hist) where G_eq = h/L and I_hist = I_L_prev.
pub fn ind_companion(inductance: f64, h: f64, i_prev: f64) -> (f64, f64) {
    let g = h / inductance;
    (g, i_prev)
}

/// Trapezoidal Rule (TR) companion initial state for a capacitor.
/// G_eq = 2C/h.  I_hist = G_eq * V_prev (assumes I_C(0) = 0 at DC OP).
pub fn cap_companion_tr(capacitance: f64, h: f64, v_prev: f64) -> (f64, f64) {
    let g = 2.0 * capacitance / h;
    (g, g * v_prev)
}

/// Advance the TR capacitor companion after a solved timestep.
///
/// Given the stored state `(G_eq, I_hist_old)` and the new capacitor voltage `v_c_new`,
/// returns the companion for the *next* step.
/// Derivation: I_hist_new = 2·G_eq·V_C_new − I_hist_old.
pub fn cap_companion_tr_advance(g_eq: f64, i_hist_old: f64, v_c_new: f64) -> (f64, f64) {
    (g_eq, 2.0 * g_eq * v_c_new - i_hist_old)
}

/// Transition a capacitor companion from BE→TR after the first BE step.
///
/// The BE companion `(g_eq_be, i_hist_be)` encodes G_be = C/h, I_hist_be = C/h·V_C_prev.
/// After solving for v_c_new, the capacitor current was I_C = G_be·V_C_new − I_hist_be.
/// Returns the TR companion for the *next* step with G_eq = 2·G_be.
pub fn cap_companion_be_to_tr(g_eq_be: f64, i_hist_be: f64, v_c_new: f64) -> (f64, f64) {
    let i_c = g_eq_be * v_c_new - i_hist_be;
    let g_eq_tr = 2.0 * g_eq_be;
    (g_eq_tr, g_eq_tr * v_c_new + i_c)
}

/// Trapezoidal Rule companion initial state for an inductor.
/// G_eq = h/(2L).  I_hist = I_L_prev (= 0 when starting from DC OP).
pub fn ind_companion_tr(inductance: f64, h: f64, i_prev: f64) -> (f64, f64) {
    let g = h / (2.0 * inductance);
    (g, i_prev)
}

/// Advance the TR inductor companion after a solved timestep.
///
/// Given the stored state `(G_eq, I_hist_old)` and new inductor voltage `v_l_new`,
/// returns the companion for the next step.
/// Derivation: I_hist_new = 2·G_eq·V_L_new + I_hist_old.
pub fn ind_companion_tr_advance(g_eq: f64, i_hist_old: f64, v_l_new: f64) -> (f64, f64) {
    (g_eq, 2.0 * g_eq * v_l_new + i_hist_old)
}

/// Transition an inductor companion from BE→TR after the first BE step.
///
/// The inductor current during the BE step was I_L = G_be·V_L_new + I_hist_be.
/// Returns the TR companion for the next step with G_eq = G_be/2.
pub fn ind_companion_be_to_tr(g_eq_be: f64, i_hist_be: f64, v_l_new: f64) -> (f64, f64) {
    let i_l = g_eq_be * v_l_new + i_hist_be;
    let g_eq_tr = g_eq_be / 2.0;
    (g_eq_tr, i_l + g_eq_tr * v_l_new)
}

/// GEAR / BDF-2 companion for a capacitor with non-uniform step.
///
/// Two-step BDF: \dot{v}_{n+1} ≈ α·v_{n+1} − β₁·v_n + β₂·v_{n-1}
/// with ρ = h_n / h_{n-1}, α = (1+2ρ)/(h(1+ρ)), β₁ = (1+ρ)/h, β₂ = ρ²/(h(1+ρ)).
///
/// Returns the Norton (G_eq, I_hist) such that i_C = G_eq·v − I_hist.
pub fn cap_companion_gear2(
    capacitance: f64,
    h: f64,
    h_prev: f64,
    v_prev: f64,
    v_prev2: f64,
) -> (f64, f64) {
    let rho = h / h_prev;
    let denom = h * (1.0 + rho);
    let g_eq = capacitance * (1.0 + 2.0 * rho) / denom;
    let i_hist = capacitance * ((1.0 + rho) / h * v_prev - (rho * rho) / denom * v_prev2);
    (g_eq, i_hist)
}

/// GEAR / BDF-2 companion for an inductor with non-uniform step.
///
/// For v_L = L·di/dt, the BDF-2 Norton form is:
///   i_{n+1} = G_eq·v_{n+1} + I_hist
/// with G_eq = h(1+ρ)/(L(1+2ρ)),
///      I_hist = ((1+ρ)²/(1+2ρ))·i_n − (ρ²/(1+2ρ))·i_{n-1}.
pub fn ind_companion_gear2(
    inductance: f64,
    h: f64,
    h_prev: f64,
    i_prev: f64,
    i_prev2: f64,
) -> (f64, f64) {
    let rho = h / h_prev;
    let denom_a = 1.0 + 2.0 * rho;
    let g_eq = h * (1.0 + rho) / (inductance * denom_a);
    let i_hist = ((1.0 + rho).powi(2) / denom_a) * i_prev - (rho * rho / denom_a) * i_prev2;
    (g_eq, i_hist)
}

/// Look up the (pos, neg) terminal node names for a named inductor in the netlist.
///
/// Panics if the inductor is not found — only called when the K-element references
/// it, so the inductor is guaranteed to exist (the sanity check would have caught it).
fn find_inductor_terminals<'a>(
    netlist: &'a fairchild_parser::Netlist,
    name: &str,
) -> (&'a str, &'a str) {
    for el in &netlist.elements {
        if let Element::Inductor {
            name: n, pos, neg, ..
        } = el
        {
            if n == name {
                return (pos, neg);
            }
        }
    }
    panic!("coupled inductor '{name}' not found in netlist")
}

/// Stamp the mutual-conductance cross-coupling for a K element.
///
/// For coupled inductors the 2×2 companion system contributes off-diagonal
/// terms: G12 * (V_pos1 - V_neg1) drives current into nodes pos2/neg2, and
/// G12 * (V_pos2 - V_neg2) drives current into nodes pos1/neg1.
///
/// `g` is G12 (typically negative for positive coupling).
fn stamp_mutual_conductance(
    a: &mut [SparseRow],
    idx: &IndexMap<String, usize>,
    pos1: &str,
    neg1: &str,
    pos2: &str,
    neg2: &str,
    g: f64,
) {
    let p1 = idx.get(pos1).copied();
    let n1 = idx.get(neg1).copied();
    let p2 = idx.get(pos2).copied();
    let n2 = idx.get(neg2).copied();

    // L2 rows from L1 voltage: G12 * (V_pos1 - V_neg1) → current at pos2/neg2
    if let Some(r2) = p2 {
        if let Some(c1) = p1 {
            a[r2][c1] += g;
        }
        if let Some(c1) = n1 {
            a[r2][c1] -= g;
        }
    }
    if let Some(r2) = n2 {
        if let Some(c1) = p1 {
            a[r2][c1] -= g;
        }
        if let Some(c1) = n1 {
            a[r2][c1] += g;
        }
    }
    // L1 rows from L2 voltage: G12 * (V_pos2 - V_neg2) → current at pos1/neg1
    if let Some(r1) = p1 {
        if let Some(c2) = p2 {
            a[r1][c2] += g;
        }
        if let Some(c2) = n2 {
            a[r1][c2] -= g;
        }
    }
    if let Some(r1) = n1 {
        if let Some(c2) = p2 {
            a[r1][c2] -= g;
        }
        if let Some(c2) = n2 {
            a[r1][c2] += g;
        }
    }
}

/// Stamp a 2-terminal value (conductance, capacitance, or 1/L) between two MNA
/// rows identified by [`crate::device::NodeId`], into a raw row-major dense
/// matrix. Ground (`None`) terminals are skipped. This is the shared kernel for
/// both the netlist-element AC/noise stamps and the device small-signal
/// reactance stamps.
pub fn stamp_2port_by_id(
    mat: &mut [Vec<f64>],
    pos: crate::device::NodeId,
    neg: crate::device::NodeId,
    val: f64,
) {
    if let Some(p) = pos {
        mat[p][p] += val;
        if let Some(n) = neg {
            mat[p][n] -= val;
            mat[n][p] -= val;
        }
    }
    if let Some(n) = neg {
        mat[n][n] += val;
    }
}

/// Stamp a 2-terminal passive value (G or C) into a raw matrix, looking node
/// names up in `idx` (ground / unknown names resolve to `None` and are skipped).
/// Thin wrapper over [`stamp_2port_by_id`]; shared by `ac.rs` and `noise.rs`.
pub fn stamp_passive_2port(
    mat: &mut [Vec<f64>],
    idx: &IndexMap<String, usize>,
    pos: &str,
    neg: &str,
    val: f64,
) {
    stamp_2port_by_id(mat, idx.get(pos).copied(), idx.get(neg).copied(), val);
}

#[cfg(test)]
mod tests {
    use super::*;
    use fairchild_parser::parse_spice;

    #[test]
    fn voltage_divider_topology_size() {
        let net = parse_spice("* divider\nV1 in 0 1.0\nR1 in mid 1000\nR2 mid 0 1000\n.op\n.end\n")
            .unwrap();
        let topo = CircuitTopology::build(&net);
        // 2 nodes (in, mid) + 1 vsource = 3×3
        assert_eq!(topo.size, 3);
    }

    #[test]
    fn rc_circuit_topology() {
        let net = parse_spice("* RC\nV1 in 0 1.0\nR1 in out 1k\nC1 out 0 1u\n.op\n.end\n").unwrap();
        let topo = CircuitTopology::build(&net);
        // nodes: in, out (2) + 1 vsource = 3
        assert_eq!(topo.size, 3);
    }

    #[test]
    fn stamp_gmin_floors_node_and_internal_rows_but_skips_vsource() {
        // 2 nodes (in, mid) + 1 vsource (rows: [0,1]=nodes, [2]=vsrc aux) and
        // then a device-internal row appended at index 3.
        let net =
            parse_spice("* divider\nV1 in 0 1.0\nR1 in mid 1k\nR2 mid 0 1k\n.op\n.end\n").unwrap();
        let mut topo = CircuitTopology::build(&net);
        assert_eq!(topo.size, 3);
        let internal = topo.allocate_extra_rows(1); // index 3, a device-internal row
        assert_eq!(internal, 3);
        assert_eq!(topo.size, 4);

        let mut a = vec![vec![0.0; 4]; 4];
        topo.stamp_gmin(&mut a, 1e-12);

        // Node rows 0,1 get the floor; the vsource aux row 2 is skipped (clean
        // KCL diagonal); the device-internal row 3 gets the floor.
        assert_eq!(a[0][0], 1e-12);
        assert_eq!(a[1][1], 1e-12);
        assert_eq!(a[2][2], 0.0, "vsource branch row must NOT receive gmin");
        assert_eq!(a[3][3], 1e-12, "device-internal row must receive gmin");
        // Off-diagonals untouched.
        assert_eq!(a[0][1], 0.0);
    }
}
