/// Modified Nodal Analysis (MNA) matrix assembler.
///
/// Matrix layout (0-based):
///   rows/cols [0 .. n_nodes)          → node voltages (ground excluded)
///   rows/cols [n_nodes .. n_nodes+m)  → voltage-source branch currents
///
/// Ground node "0" is eliminated from the matrix.
use fairchild_parser::{Element, Netlist};
use indexmap::IndexMap;

use crate::error::SimError;

/// The topology/index maps for a circuit — built once, reused across time steps.
///
/// Row layout:
///   `[0 .. n_nodes)`             — circuit node voltages
///   `[n_nodes .. n_nodes+n_vsrc)` — voltage-source branch currents
///   `[n_nodes+n_vsrc .. size)`   — device-internal nodes (e.g. OSDI flow
///                                  branches generated by potential
///                                  contributions in Verilog-A models)
#[derive(Clone)]
pub struct CircuitTopology {
    /// Map from node name → matrix row/col (ground excluded).
    pub node_index: IndexMap<String, usize>,
    /// Map from voltage source name → aux current index within A/b.
    pub vsrc_index: IndexMap<String, usize>,
    /// Total matrix dimension = n_nodes + n_vsources + n_device_extras.
    pub size: usize,
}

impl CircuitTopology {
    pub fn build(netlist: &Netlist) -> CircuitTopology {
        let (node_index, vsrc_index) = index_circuit(netlist);
        let size = node_index.len() + vsrc_index.len();
        CircuitTopology {
            node_index,
            vsrc_index,
            size,
        }
    }

    pub fn n_nodes(&self) -> usize {
        self.node_index.len()
    }

    /// Allocate `n` contiguous MNA rows for device-internal nodes (e.g. OSDI
    /// flow-branch nodes from potential contributions).  Returns the first
    /// allocated index.  Called by `build_devices` once per device that
    /// reports `num_extra_nodes() > 0`.
    pub fn allocate_extra_rows(&mut self, n: usize) -> usize {
        let start = self.size;
        self.size += n;
        start
    }

    /// Retrieve a node voltage from a solution vector.
    pub fn node_voltage(&self, node: &str, x: &[f64]) -> Result<f64, SimError> {
        if node == "0" || node == "gnd" {
            return Ok(0.0);
        }
        self.node_index
            .get(node)
            .map(|&i| x[i])
            .ok_or_else(|| SimError::UnknownNode(node.to_string()))
    }

    /// Retrieve a voltage-source branch current from a solution vector.
    pub fn vsrc_current(&self, vsrc_name: &str, x: &[f64]) -> Result<f64, SimError> {
        self.vsrc_index
            .get(vsrc_name)
            .map(|&i| x[self.n_nodes() + i])
            .ok_or_else(|| SimError::UnknownNode(vsrc_name.to_string()))
    }
}

/// An assembled MNA system: A·x = b.
pub struct MnaMatrix {
    pub a: Vec<Vec<f64>>,
    pub b: Vec<f64>,
}

impl MnaMatrix {
    fn new(size: usize) -> Self {
        MnaMatrix {
            a: vec![vec![0.0f64; size]; size],
            b: vec![0.0f64; size],
        }
    }

    /// Build a zero-filled MnaMatrix at the given dimension.  Useful for
    /// diagnostic passes that need a clean scratch matrix without going
    /// through the netlist stamper.
    pub fn zeros(size: usize) -> Self {
        Self::new(size)
    }

    /// Zero every cell of `a` and every entry of `b` in place.  Used by
    /// the hot NR / transient loops to reuse a single `MnaMatrix`
    /// allocation across iterations instead of paying N+1 heap
    /// allocations per stamp.
    pub fn clear(&mut self) {
        for row in self.a.iter_mut() {
            row.fill(0.0);
        }
        self.b.fill(0.0);
    }
}

// ---------------------------------------------------------------------------
// DC stamp (time-independent elements, or companion equivalents for C/L)
// ---------------------------------------------------------------------------

/// In-place version of [`stamp_netlist_scaled`].  `mat` is cleared and
/// then filled — the caller owns the allocation and reuses it across NR
/// iterations to avoid the N+1 heap allocations per stamp.
pub fn stamp_netlist_scaled_in_place(
    mat: &mut MnaMatrix,
    topo: &CircuitTopology,
    netlist: &Netlist,
    source_scale: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
) {
    stamp_netlist_in_place(mat, topo, netlist, 0.0, cap_state, ind_state);
    if (source_scale - 1.0).abs() < 1e-15 {
        return;
    }
    let n_nodes = topo.n_nodes();
    for (name, &vi_idx) in &topo.vsrc_index {
        let vi = n_nodes + vi_idx;
        if let Some(Element::VoltageSource { waveform, .. }) = netlist
            .elements
            .iter()
            .find(|e| matches!(e, Element::VoltageSource { name: n, .. } if n == name))
        {
            let v_full = waveform.at(0.0);
            mat.b[vi] = mat.b[vi] - v_full + v_full * source_scale;
        }
    }
    for el in &netlist.elements {
        if let Element::CurrentSource {
            pos, neg, waveform, ..
        } = el
        {
            let i_full = waveform.at(0.0);
            if i_full == 0.0 {
                continue;
            }
            let delta = i_full * (source_scale - 1.0);
            if let Some(&p) = topo.node_index.get(pos) {
                mat.b[p] -= delta;
            }
            if let Some(&n) = topo.node_index.get(neg) {
                mat.b[n] += delta;
            }
        }
    }
}

/// Allocating variant: produces a fresh `MnaMatrix`.  Kept for non-hot
/// call sites (one-off diagnostics, AC side-car G assembly).  The NR
/// inner loops should call [`stamp_netlist_scaled_in_place`] against a
/// reused matrix instead.
pub fn stamp_netlist_scaled(
    topo: &CircuitTopology,
    netlist: &Netlist,
    source_scale: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
) -> MnaMatrix {
    let mut mat = stamp_netlist(topo, netlist, 0.0, cap_state, ind_state);
    if (source_scale - 1.0).abs() < 1e-15 {
        return mat;
    }
    // Re-scale source contributions: voltage sources stamp into b[vi], current sources into b[node].
    // Rather than re-stamping from scratch, rescale: b[vi] already has waveform.at(0) from
    // stamp_netlist (t=0 = DC value). We just scale b entries for source rows.
    let n_nodes = topo.n_nodes();
    for (name, &vi_idx) in &topo.vsrc_index {
        let vi = n_nodes + vi_idx;
        // Find the source's waveform value and rescale.
        if let Some(Element::VoltageSource { waveform, .. }) = netlist
            .elements
            .iter()
            .find(|e| matches!(e, Element::VoltageSource { name: n, .. } if n == name))
        {
            let v_full = waveform.at(0.0);
            // The stamp put v_full into b[vi]; replace with v_full * source_scale.
            mat.b[vi] = mat.b[vi] - v_full + v_full * source_scale;
        }
    }
    for el in &netlist.elements {
        if let Element::CurrentSource {
            pos, neg, waveform, ..
        } = el
        {
            let i_full = waveform.at(0.0);
            if i_full == 0.0 {
                continue;
            }
            let delta = i_full * (source_scale - 1.0);
            // stamp_current_source: b[pos] -= i, b[neg] += i. Scale correction = delta.
            if let Some(&p) = topo.node_index.get(pos) {
                mat.b[p] -= delta;
            }
            if let Some(&n) = topo.node_index.get(neg) {
                mat.b[n] += delta;
            }
        }
    }
    mat
}

/// In-place stamp.  Clears `mat` then fills the full MNA system.  The
/// caller owns the allocation — used by the NR / transient inner loops
/// to skip per-iteration heap allocation.
pub fn stamp_netlist_in_place(
    mat: &mut MnaMatrix,
    topo: &CircuitTopology,
    netlist: &Netlist,
    t: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
) {
    mat.clear();
    stamp_netlist_into(mat, topo, netlist, t, cap_state, ind_state);
}

/// Allocating variant: produces a fresh `MnaMatrix`.  Kept for non-hot
/// callers (DC OP one-shots, AC G-matrix assembly, diagnostic dumps).
///
/// `t`           — current simulation time (used for PULSE sources)
/// `cap_state`   — map from capacitor name → (G_eq, I_hist) BE companion pair
/// `ind_state`   — map from inductor name  → (G_eq, I_hist) BE companion pair
pub fn stamp_netlist(
    topo: &CircuitTopology,
    netlist: &Netlist,
    t: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
) -> MnaMatrix {
    let mut mat = MnaMatrix::new(topo.size);
    stamp_netlist_into(&mut mat, topo, netlist, t, cap_state, ind_state);
    mat
}

/// Internal shared stamping body.  Assumes `mat` is already zeroed at
/// the right size (caller responsibility).
fn stamp_netlist_into(
    mat: &mut MnaMatrix,
    topo: &CircuitTopology,
    netlist: &Netlist,
    t: f64,
    cap_state: &IndexMap<String, (f64, f64)>,
    ind_state: &IndexMap<String, (f64, f64)>,
) {
    use std::collections::HashMap;

    let n_nodes = topo.n_nodes();

    // Build coupled-inductor map: inductor_name → (partner_name, coupling_k)
    // and a value map for inductance lookups.
    let mut coupled_map: HashMap<String, (String, f64)> = HashMap::new();
    let mut ind_values: HashMap<String, f64> = HashMap::new();
    for el in &netlist.elements {
        if let Element::Inductor {
            name, inductance, ..
        } = el
        {
            ind_values.insert(name.clone(), *inductance);
        }
        if let Element::CoupledInductors {
            l1, l2, coupling, ..
        } = el
        {
            coupled_map.insert(l1.clone(), (l2.clone(), *coupling));
            coupled_map.insert(l2.clone(), (l1.clone(), *coupling));
        }
    }

    for el in &netlist.elements {
        match el {
            Element::Resistor {
                pos,
                neg,
                resistance,
                ..
            } => {
                stamp_conductance(&mut mat.a, &topo.node_index, pos, neg, 1.0 / resistance);
            }
            Element::Capacitor { name, pos, neg, .. } => {
                if let Some(&(g_eq, i_hist)) = cap_state.get(name) {
                    stamp_conductance(&mut mat.a, &topo.node_index, pos, neg, g_eq);
                    // BE companion: KCL at pos gives b[pos] += I_hist.
                    // stamp_current_source(neg, pos, v) adds v to b[pos].
                    stamp_current_source(&mut mat.b, &topo.node_index, neg, pos, i_hist);
                }
                // Capacitor absent from cap_state = open circuit (correct for DC OP).
            }
            Element::Inductor { name, pos, neg, .. } => {
                if let Some(&(g_eq, i_hist)) = ind_state.get(name) {
                    // For coupled inductors, skip the standalone self-conductance stamp;
                    // the CoupledInductors arm below handles the full 2×2 companion.
                    if !coupled_map.contains_key(name) {
                        stamp_conductance(&mut mat.a, &topo.node_index, pos, neg, g_eq);
                    }
                    // Always stamp history current source.
                    stamp_current_source(&mut mat.b, &topo.node_index, pos, neg, i_hist);
                }
                // If not in ind_state (no transient yet), inductor = open circuit at DC.
            }
            Element::CoupledInductors {
                l1, l2, coupling, ..
            } => {
                // Both inductors must be in ind_state (transient); skip at DC.
                let Some(&(g_eq1, _)) = ind_state.get(l1) else {
                    continue;
                };
                let Some(&(g_eq2, _)) = ind_state.get(l2) else {
                    continue;
                };
                let Some(&val1) = ind_values.get(l1) else {
                    continue;
                };
                let Some(&val2) = ind_values.get(l2) else {
                    continue;
                };
                let k = *coupling;
                let m = k * (val1 * val2).sqrt();
                let det = val1 * val2 - m * m; // = val1*val2*(1-k²)
                if det.abs() < 1e-40 {
                    continue;
                } // k≈1: degenerate, skip
                  // Extract h from g_eq = h/L  =>  h = g_eq * L
                let h = g_eq1 * val1;
                let g11 = h * val2 / det;
                let g22 = h * val1 / det;
                let g12 = -h * m / det;

                let (pos1, neg1) = find_inductor_terminals(netlist, l1);
                let (pos2, neg2) = find_inductor_terminals(netlist, l2);

                stamp_conductance(&mut mat.a, &topo.node_index, pos1, neg1, g11);
                stamp_conductance(&mut mat.a, &topo.node_index, pos2, neg2, g22);
                stamp_mutual_conductance(&mut mat.a, &topo.node_index, pos1, neg1, pos2, neg2, g12);

                // Verify g_eq2-derived h is consistent (both inductors share same step).
                let _ = g_eq2; // used above implicitly; avoid unused variable warning
            }
            Element::VoltageSource {
                name,
                pos,
                neg,
                waveform,
            } => {
                let vi = n_nodes + topo.vsrc_index[name];
                stamp_vsource(
                    &mut mat.a,
                    &mut mat.b,
                    &topo.node_index,
                    pos,
                    neg,
                    vi,
                    waveform.at(t),
                );
            }
            Element::CurrentSource {
                pos, neg, waveform, ..
            } => {
                // SPICE: current flows from n+ through source to n- → subtract from n+, add to n-.
                stamp_current_source(&mut mat.b, &topo.node_index, pos, neg, waveform.at(t));
            }
            Element::Diode { .. }
            | Element::Mosfet { .. }
            | Element::Bjt { .. }
            | Element::XOsdi { .. }
            | Element::Behavioral { .. }
            | Element::TransmissionLine { .. } => {
                // Stamped by the Device trait inside the Newton-Raphson loop
                // (the T-line carries time-dependent history sources).
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Stamp primitives
// ---------------------------------------------------------------------------

/// Add a conductance G between pos and neg (same as resistor with R=1/G).
pub fn stamp_conductance(
    a: &mut [Vec<f64>],
    idx: &IndexMap<String, usize>,
    pos: &str,
    neg: &str,
    g: f64,
) {
    if let Some(&p) = idx.get(pos) {
        a[p][p] += g;
        if let Some(&n) = idx.get(neg) {
            a[p][n] -= g;
            a[n][p] -= g;
        }
    }
    if let Some(&n) = idx.get(neg) {
        a[n][n] += g;
    }
}

/// Stamp a voltage source at aux row `vi`: V(pos) - V(neg) = value.
fn stamp_vsource(
    a: &mut [Vec<f64>],
    b: &mut [f64],
    idx: &IndexMap<String, usize>,
    pos: &str,
    neg: &str,
    vi: usize,
    value: f64,
) {
    if let Some(&p) = idx.get(pos) {
        a[p][vi] += 1.0;
        a[vi][p] += 1.0;
    }
    if let Some(&n) = idx.get(neg) {
        a[n][vi] -= 1.0;
        a[vi][n] -= 1.0;
    }
    b[vi] += value;
}

/// Stamp a current source.
/// SPICE convention: positive current flows from pos through source to neg.
///   → b[pos] -= value,  b[neg] += value
fn stamp_current_source(
    b: &mut [f64],
    idx: &IndexMap<String, usize>,
    pos: &str,
    neg: &str,
    value: f64,
) {
    if let Some(&p) = idx.get(pos) {
        b[p] -= value;
    }
    if let Some(&n) = idx.get(neg) {
        b[n] += value;
    }
}

// ---------------------------------------------------------------------------
// Index builder
// ---------------------------------------------------------------------------

fn index_circuit(netlist: &Netlist) -> (IndexMap<String, usize>, IndexMap<String, usize>) {
    let mut node_index: IndexMap<String, usize> = IndexMap::new();
    let mut vsrc_index: IndexMap<String, usize> = IndexMap::new();

    for el in &netlist.elements {
        match el {
            Element::Resistor { pos, neg, .. }
            | Element::Capacitor { pos, neg, .. }
            | Element::Inductor { pos, neg, .. }
            | Element::CurrentSource { pos, neg, .. } => {
                add_node(&mut node_index, pos);
                add_node(&mut node_index, neg);
            }
            Element::Diode { anode, cathode, .. } => {
                add_node(&mut node_index, anode);
                add_node(&mut node_index, cathode);
            }
            Element::Mosfet {
                drain,
                gate,
                source,
                bulk,
                ..
            } => {
                add_node(&mut node_index, drain);
                add_node(&mut node_index, gate);
                add_node(&mut node_index, source);
                add_node(&mut node_index, bulk);
            }
            Element::Bjt {
                collector,
                base,
                emitter,
                substrate,
                ..
            } => {
                add_node(&mut node_index, collector);
                add_node(&mut node_index, base);
                add_node(&mut node_index, emitter);
                add_node(&mut node_index, substrate);
            }
            Element::VoltageSource { name, pos, neg, .. } => {
                add_node(&mut node_index, pos);
                add_node(&mut node_index, neg);
                let n = vsrc_index.len();
                vsrc_index.entry(name.clone()).or_insert(n);
            }
            Element::XOsdi { nets, .. } => {
                for net in nets {
                    add_node(&mut node_index, net);
                }
            }
            Element::Behavioral {
                name,
                pos,
                neg,
                kind,
                ..
            } => {
                add_node(&mut node_index, pos);
                add_node(&mut node_index, neg);
                if *kind == fairchild_parser::BehavioralKind::Voltage {
                    let n = vsrc_index.len();
                    vsrc_index.entry(name.clone()).or_insert(n);
                }
            }
            Element::CoupledInductors { .. } => {
                // No new nodes — L1 and L2 terminals already registered by their
                // Inductor elements.
            }
            Element::TransmissionLine {
                a_pos,
                a_neg,
                b_pos,
                b_neg,
                ..
            } => {
                add_node(&mut node_index, a_pos);
                add_node(&mut node_index, a_neg);
                add_node(&mut node_index, b_pos);
                add_node(&mut node_index, b_neg);
                // The two branch-current rows are device extra nodes, allocated
                // by build_devices via num_extra_nodes/bind_extra_nodes.
            }
        }
    }

    (node_index, vsrc_index)
}

fn add_node(map: &mut IndexMap<String, usize>, node: &str) {
    if node != "0" {
        let n = map.len();
        map.entry(node.to_string()).or_insert(n);
    }
}

/// Backward Euler companion state for a capacitor at one time step.
/// Returns (G_eq, I_hist) where G_eq = C/h and I_hist = G_eq * V_prev.
pub fn cap_companion(capacitance: f64, h: f64, v_prev: f64) -> (f64, f64) {
    let g = capacitance / h;
    (g, g * v_prev)
}

/// Backward Euler companion state for an inductor at one time step.
/// Returns (G_eq, I_hist) where G_eq = h/L and I_hist = I_L_prev.
pub fn ind_companion(inductance: f64, h: f64, i_prev: f64) -> (f64, f64) {
    let g = h / inductance;
    (g, i_prev)
}

/// Trapezoidal Rule (TR) companion initial state for a capacitor.
/// G_eq = 2C/h.  I_hist = G_eq * V_prev (assumes I_C(0) = 0 at DC OP).
pub fn cap_companion_tr(capacitance: f64, h: f64, v_prev: f64) -> (f64, f64) {
    let g = 2.0 * capacitance / h;
    (g, g * v_prev)
}

/// Advance the TR capacitor companion after a solved timestep.
///
/// Given the stored state `(G_eq, I_hist_old)` and the new capacitor voltage `v_c_new`,
/// returns the companion for the *next* step.
/// Derivation: I_hist_new = 2·G_eq·V_C_new − I_hist_old.
pub fn cap_companion_tr_advance(g_eq: f64, i_hist_old: f64, v_c_new: f64) -> (f64, f64) {
    (g_eq, 2.0 * g_eq * v_c_new - i_hist_old)
}

/// Transition a capacitor companion from BE→TR after the first BE step.
///
/// The BE companion `(g_eq_be, i_hist_be)` encodes G_be = C/h, I_hist_be = C/h·V_C_prev.
/// After solving for v_c_new, the capacitor current was I_C = G_be·V_C_new − I_hist_be.
/// Returns the TR companion for the *next* step with G_eq = 2·G_be.
pub fn cap_companion_be_to_tr(g_eq_be: f64, i_hist_be: f64, v_c_new: f64) -> (f64, f64) {
    let i_c = g_eq_be * v_c_new - i_hist_be;
    let g_eq_tr = 2.0 * g_eq_be;
    (g_eq_tr, g_eq_tr * v_c_new + i_c)
}

/// Trapezoidal Rule companion initial state for an inductor.
/// G_eq = h/(2L).  I_hist = I_L_prev (= 0 when starting from DC OP).
pub fn ind_companion_tr(inductance: f64, h: f64, i_prev: f64) -> (f64, f64) {
    let g = h / (2.0 * inductance);
    (g, i_prev)
}

/// Advance the TR inductor companion after a solved timestep.
///
/// Given the stored state `(G_eq, I_hist_old)` and new inductor voltage `v_l_new`,
/// returns the companion for the next step.
/// Derivation: I_hist_new = 2·G_eq·V_L_new + I_hist_old.
pub fn ind_companion_tr_advance(g_eq: f64, i_hist_old: f64, v_l_new: f64) -> (f64, f64) {
    (g_eq, 2.0 * g_eq * v_l_new + i_hist_old)
}

/// Transition an inductor companion from BE→TR after the first BE step.
///
/// The inductor current during the BE step was I_L = G_be·V_L_new + I_hist_be.
/// Returns the TR companion for the next step with G_eq = G_be/2.
pub fn ind_companion_be_to_tr(g_eq_be: f64, i_hist_be: f64, v_l_new: f64) -> (f64, f64) {
    let i_l = g_eq_be * v_l_new + i_hist_be;
    let g_eq_tr = g_eq_be / 2.0;
    (g_eq_tr, i_l + g_eq_tr * v_l_new)
}

/// GEAR / BDF-2 companion for a capacitor with non-uniform step.
///
/// Two-step BDF: \dot{v}_{n+1} ≈ α·v_{n+1} − β₁·v_n + β₂·v_{n-1}
/// with ρ = h_n / h_{n-1}, α = (1+2ρ)/(h(1+ρ)), β₁ = (1+ρ)/h, β₂ = ρ²/(h(1+ρ)).
///
/// Returns the Norton (G_eq, I_hist) such that i_C = G_eq·v − I_hist.
pub fn cap_companion_gear2(
    capacitance: f64,
    h: f64,
    h_prev: f64,
    v_prev: f64,
    v_prev2: f64,
) -> (f64, f64) {
    let rho = h / h_prev;
    let denom = h * (1.0 + rho);
    let g_eq = capacitance * (1.0 + 2.0 * rho) / denom;
    let i_hist = capacitance * ((1.0 + rho) / h * v_prev - (rho * rho) / denom * v_prev2);
    (g_eq, i_hist)
}

/// GEAR / BDF-2 companion for an inductor with non-uniform step.
///
/// For v_L = L·di/dt, the BDF-2 Norton form is:
///   i_{n+1} = G_eq·v_{n+1} + I_hist
/// with G_eq = h(1+ρ)/(L(1+2ρ)),
///      I_hist = ((1+ρ)²/(1+2ρ))·i_n − (ρ²/(1+2ρ))·i_{n-1}.
pub fn ind_companion_gear2(
    inductance: f64,
    h: f64,
    h_prev: f64,
    i_prev: f64,
    i_prev2: f64,
) -> (f64, f64) {
    let rho = h / h_prev;
    let denom_a = 1.0 + 2.0 * rho;
    let g_eq = h * (1.0 + rho) / (inductance * denom_a);
    let i_hist = ((1.0 + rho).powi(2) / denom_a) * i_prev - (rho * rho / denom_a) * i_prev2;
    (g_eq, i_hist)
}

/// Look up the (pos, neg) terminal node names for a named inductor in the netlist.
///
/// Panics if the inductor is not found — only called when the K-element references
/// it, so the inductor is guaranteed to exist (the sanity check would have caught it).
fn find_inductor_terminals<'a>(
    netlist: &'a fairchild_parser::Netlist,
    name: &str,
) -> (&'a str, &'a str) {
    for el in &netlist.elements {
        if let Element::Inductor {
            name: n, pos, neg, ..
        } = el
        {
            if n == name {
                return (pos, neg);
            }
        }
    }
    panic!("coupled inductor '{name}' not found in netlist")
}

/// Stamp the mutual-conductance cross-coupling for a K element.
///
/// For coupled inductors the 2×2 companion system contributes off-diagonal
/// terms: G12 * (V_pos1 - V_neg1) drives current into nodes pos2/neg2, and
/// G12 * (V_pos2 - V_neg2) drives current into nodes pos1/neg1.
///
/// `g` is G12 (typically negative for positive coupling).
fn stamp_mutual_conductance(
    a: &mut [Vec<f64>],
    idx: &IndexMap<String, usize>,
    pos1: &str,
    neg1: &str,
    pos2: &str,
    neg2: &str,
    g: f64,
) {
    let p1 = idx.get(pos1).copied();
    let n1 = idx.get(neg1).copied();
    let p2 = idx.get(pos2).copied();
    let n2 = idx.get(neg2).copied();

    // L2 rows from L1 voltage: G12 * (V_pos1 - V_neg1) → current at pos2/neg2
    if let Some(r2) = p2 {
        if let Some(c1) = p1 {
            a[r2][c1] += g;
        }
        if let Some(c1) = n1 {
            a[r2][c1] -= g;
        }
    }
    if let Some(r2) = n2 {
        if let Some(c1) = p1 {
            a[r2][c1] -= g;
        }
        if let Some(c1) = n1 {
            a[r2][c1] += g;
        }
    }
    // L1 rows from L2 voltage: G12 * (V_pos2 - V_neg2) → current at pos1/neg1
    if let Some(r1) = p1 {
        if let Some(c2) = p2 {
            a[r1][c2] += g;
        }
        if let Some(c2) = n2 {
            a[r1][c2] -= g;
        }
    }
    if let Some(r1) = n1 {
        if let Some(c2) = p2 {
            a[r1][c2] -= g;
        }
        if let Some(c2) = n2 {
            a[r1][c2] += g;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use fairchild_parser::parse_spice;

    #[test]
    fn voltage_divider_topology_size() {
        let net = parse_spice("* divider\nV1 in 0 1.0\nR1 in mid 1000\nR2 mid 0 1000\n.op\n.end\n")
            .unwrap();
        let topo = CircuitTopology::build(&net);
        // 2 nodes (in, mid) + 1 vsource = 3×3
        assert_eq!(topo.size, 3);
    }

    #[test]
    fn rc_circuit_topology() {
        let net = parse_spice("* RC\nV1 in 0 1.0\nR1 in out 1k\nC1 out 0 1u\n.op\n.end\n").unwrap();
        let topo = CircuitTopology::build(&net);
        // nodes: in, out (2) + 1 vsource = 3
        assert_eq!(topo.size, 3);
    }
}
